package trikita.anvil.cardview.v7;

import android.support.v7.widget.CardView;
import android.view.View;
import java.lang.Boolean;
import java.lang.Float;
import java.lang.Integer;
import java.lang.Void;
import trikita.anvil.Anvil;
import trikita.anvil.BaseDSL;

/**
 * DSL for creating views and settings their attributes.
 * This file has been generated by {@code gradle generateCardViewv7DSL}.
 * It contains views and their setters from the library cardview-v7.
 * Please, don't edit it manually unless for debugging.
 */
public final class CardViewv7DSL extends BaseDSL {
  public static CardViewv7DSL.ViewClassResult cardView() {
    return v(CardView.class);
  }

  public static Void cardView(Anvil.Renderable r) {
    return v(CardView.class, r);
  }

  public static Void cardBackgroundColor(int arg) {
    return CardViewv7DSL.attr(CardBackgroundColorFunc8567756a.instance, arg);
  }

  public static Void cardElevation(float arg) {
    return CardViewv7DSL.attr(CardElevationFunce0893188.instance, arg);
  }

  public static Void maxCardElevation(float arg) {
    return CardViewv7DSL.attr(MaxCardElevationFunce0893188.instance, arg);
  }

  public static Void minimumHeight(int arg) {
    return CardViewv7DSL.attr(MinimumHeightFunc8567756a.instance, arg);
  }

  public static Void minimumWidth(int arg) {
    return CardViewv7DSL.attr(MinimumWidthFunc8567756a.instance, arg);
  }

  public static Void preventCornerOverlap(boolean arg) {
    return CardViewv7DSL.attr(PreventCornerOverlapFunc148d6054.instance, arg);
  }

  public static Void radius(float arg) {
    return CardViewv7DSL.attr(RadiusFunce0893188.instance, arg);
  }

  public static Void useCompatPadding(boolean arg) {
    return CardViewv7DSL.attr(UseCompatPaddingFunc148d6054.instance, arg);
  }

  private static final class CardBackgroundColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final CardBackgroundColorFunc8567756a instance = new CardBackgroundColorFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CardView) {
        ((CardView) v).setCardBackgroundColor(arg);
      }
    }
  }

  private static final class CardElevationFunce0893188 implements Anvil.AttrFunc<Float> {
    public static final CardElevationFunce0893188 instance = new CardElevationFunce0893188();

    public void apply(View v, final Float arg, final Float old) {
      if (v instanceof CardView) {
        ((CardView) v).setCardElevation(arg);
      }
    }
  }

  private static final class MaxCardElevationFunce0893188 implements Anvil.AttrFunc<Float> {
    public static final MaxCardElevationFunce0893188 instance = new MaxCardElevationFunce0893188();

    public void apply(View v, final Float arg, final Float old) {
      if (v instanceof CardView) {
        ((CardView) v).setMaxCardElevation(arg);
      }
    }
  }

  private static final class MinimumHeightFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final MinimumHeightFunc8567756a instance = new MinimumHeightFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CardView) {
        ((CardView) v).setMinimumHeight(arg);
      }
    }
  }

  private static final class MinimumWidthFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final MinimumWidthFunc8567756a instance = new MinimumWidthFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof CardView) {
        ((CardView) v).setMinimumWidth(arg);
      }
    }
  }

  private static final class PreventCornerOverlapFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final PreventCornerOverlapFunc148d6054 instance = new PreventCornerOverlapFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof CardView) {
        ((CardView) v).setPreventCornerOverlap(arg);
      }
    }
  }

  private static final class RadiusFunce0893188 implements Anvil.AttrFunc<Float> {
    public static final RadiusFunce0893188 instance = new RadiusFunce0893188();

    public void apply(View v, final Float arg, final Float old) {
      if (v instanceof CardView) {
        ((CardView) v).setRadius(arg);
      }
    }
  }

  private static final class UseCompatPaddingFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final UseCompatPaddingFunc148d6054 instance = new UseCompatPaddingFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof CardView) {
        ((CardView) v).setUseCompatPadding(arg);
      }
    }
  }
}
