language: android

env:
  global:
    - GRADLE_OPTS=-Xmx512m

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
  licenses:
    - '.+'

jdk:
  - oraclejdk8

script:
  - ./gradlew assemble anvil:check --stacktrace
