language: android

env:
  global:
    - GRADLE_OPTS=-Xmx512m

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"

jdk:
  - oraclejdk8

script:
  - ./gradlew assemble anvil:check --stacktrace
