@file:Suppress("DEPRECATION", "UNCHECKED_CAST", "MemberVisibilityCanBePrivate", "unused")

package dev.inkremental.dsl.google.android.material

import android.content.res.ColorStateList
import android.graphics.PorterDuff
import android.graphics.Typeface
import android.graphics.drawable.Drawable
import android.view.MenuItem
import android.view.View
import androidx.core.content.res.ResourcesCompat
import com.google.android.material.animation.MotionSpec
import com.google.android.material.appbar.AppBarLayout
import com.google.android.material.appbar.CollapsingToolbarLayout
import com.google.android.material.bottomappbar.BottomAppBar
import com.google.android.material.bottomnavigation.BottomNavigationView
import com.google.android.material.button.MaterialButton
import com.google.android.material.button.MaterialButtonToggleGroup
import com.google.android.material.card.MaterialCardView
import com.google.android.material.checkbox.MaterialCheckBox
import com.google.android.material.chip.Chip
import com.google.android.material.chip.ChipDrawable
import com.google.android.material.chip.ChipGroup
import com.google.android.material.circularreveal.CircularRevealFrameLayout
import com.google.android.material.circularreveal.CircularRevealGridLayout
import com.google.android.material.circularreveal.CircularRevealLinearLayout
import com.google.android.material.circularreveal.CircularRevealRelativeLayout
import com.google.android.material.circularreveal.CircularRevealWidget
import com.google.android.material.circularreveal.cardview.CircularRevealCardView
import com.google.android.material.floatingactionbutton.ExtendedFloatingActionButton
import com.google.android.material.floatingactionbutton.FloatingActionButton
import com.google.android.material.imageview.ShapeableImageView
import com.google.android.material.internal.CheckableImageButton
import com.google.android.material.internal.FlowLayout
import com.google.android.material.internal.NavigationMenuItemView
import com.google.android.material.internal.ScrimInsetsFrameLayout
import com.google.android.material.navigation.NavigationView
import com.google.android.material.radiobutton.MaterialRadioButton
import com.google.android.material.resources.TextAppearance
import com.google.android.material.shape.ShapeAppearanceModel
import com.google.android.material.slider.Slider
import com.google.android.material.switchmaterial.SwitchMaterial
import com.google.android.material.tabs.TabLayout
import com.google.android.material.textfield.TextInputLayout
import dev.inkremental.Inkremental
import dev.inkremental.dip
import kotlin.Any
import kotlin.Boolean
import kotlin.CharSequence
import kotlin.Float
import kotlin.Function
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Suppress
import kotlin.Unit

/**
 * DSL for creating views and settings their attributes.
 * This file has been generated by
 * {@code gradle MaterialSetter}
 * It contains views and their setters for the library material-1.2.0-alpha04.
 * Please, don't edit it manually unless for debugging.
 */
object MaterialSetter : Inkremental.AttributeSetter<Any> {
  override fun set(
    v: View,
    name: String,
    arg: Any?,
    old: Any?
  ): Boolean = when (name) {
    "expanded" -> when {
      v is AppBarLayout && arg is Boolean -> {
        v.setExpanded(arg)
        true
      }
      v is FloatingActionButton && arg is Boolean -> {
        v.setExpanded(arg)
        true
      }
      else -> false
    }
    "liftOnScroll" -> when {
      v is AppBarLayout && arg is Boolean -> {
        v.setLiftOnScroll(arg)
        true
      }
      else -> false
    }
    "liftOnScrollTargetViewId" -> when {
      v is AppBarLayout && arg is Int -> {
        v.setLiftOnScrollTargetViewId(arg)
        true
      }
      else -> false
    }
    "liftable" -> when {
      v is AppBarLayout && arg is Boolean -> {
        v.setLiftable(arg)
        true
      }
      else -> false
    }
    "lifted" -> when {
      v is AppBarLayout && arg is Boolean -> {
        v.setLifted(arg)
        true
      }
      else -> false
    }
    "statusBarForeground" -> when {
      v is AppBarLayout && arg is Drawable? -> {
        v.setStatusBarForeground(arg)
        true
      }
      else -> false
    }
    "statusBarForegroundColor" -> when {
      v is AppBarLayout && arg is Int -> {
        v.setStatusBarForegroundColor(arg)
        true
      }
      else -> false
    }
    "statusBarForegroundResource" -> when {
      v is AppBarLayout && arg is Int -> {
        v.setStatusBarForegroundResource(arg)
        true
      }
      else -> false
    }
    "collapsedTitleGravity" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setCollapsedTitleGravity(arg)
        true
      }
      else -> false
    }
    "collapsedTitleTextAppearance" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setCollapsedTitleTextAppearance(arg)
        true
      }
      else -> false
    }
    "collapsedTitleTextColor" -> when {
      v is CollapsingToolbarLayout && arg is ColorStateList -> {
        v.setCollapsedTitleTextColor(arg)
        true
      }
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setCollapsedTitleTextColor(arg)
        true
      }
      else -> false
    }
    "collapsedTitleTypeface" -> when {
      v is CollapsingToolbarLayout && arg is Typeface? -> {
        v.setCollapsedTitleTypeface(arg)
        true
      }
      else -> false
    }
    "contentScrim" -> when {
      v is CollapsingToolbarLayout && arg is Drawable? -> {
        v.setContentScrim(arg)
        true
      }
      else -> false
    }
    "contentScrimColor" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setContentScrimColor(arg)
        true
      }
      else -> false
    }
    "contentScrimResource" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setContentScrimResource(arg)
        true
      }
      else -> false
    }
    "expandedTitleColor" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setExpandedTitleColor(arg)
        true
      }
      else -> false
    }
    "expandedTitleGravity" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setExpandedTitleGravity(arg)
        true
      }
      else -> false
    }
    "expandedTitleMarginBottom" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setExpandedTitleMarginBottom(arg)
        true
      }
      else -> false
    }
    "expandedTitleMarginEnd" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setExpandedTitleMarginEnd(arg)
        true
      }
      else -> false
    }
    "expandedTitleMarginStart" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setExpandedTitleMarginStart(arg)
        true
      }
      else -> false
    }
    "expandedTitleMarginTop" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setExpandedTitleMarginTop(arg)
        true
      }
      else -> false
    }
    "expandedTitleTextAppearance" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setExpandedTitleTextAppearance(arg)
        true
      }
      else -> false
    }
    "expandedTitleTextColor" -> when {
      v is CollapsingToolbarLayout && arg is ColorStateList -> {
        v.setExpandedTitleTextColor(arg)
        true
      }
      else -> false
    }
    "expandedTitleTypeface" -> when {
      v is CollapsingToolbarLayout && arg is Typeface? -> {
        v.setExpandedTitleTypeface(arg)
        true
      }
      else -> false
    }
    "scrimAnimationDuration" -> when {
      v is CollapsingToolbarLayout && arg is Long -> {
        v.setScrimAnimationDuration(arg)
        true
      }
      else -> false
    }
    "scrimVisibleHeightTrigger" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setScrimVisibleHeightTrigger(arg)
        true
      }
      else -> false
    }
    "scrimsShown" -> when {
      v is CollapsingToolbarLayout && arg is Boolean -> {
        v.setScrimsShown(arg)
        true
      }
      else -> false
    }
    "statusBarScrim" -> when {
      v is CollapsingToolbarLayout && arg is Drawable? -> {
        v.setStatusBarScrim(arg)
        true
      }
      else -> false
    }
    "statusBarScrimColor" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setStatusBarScrimColor(arg)
        true
      }
      else -> false
    }
    "statusBarScrimResource" -> when {
      v is CollapsingToolbarLayout && arg is Int -> {
        v.setStatusBarScrimResource(arg)
        true
      }
      else -> false
    }
    "title" -> when {
      v is CollapsingToolbarLayout && arg is CharSequence? -> {
        v.setTitle(arg)
        true
      }
      else -> false
    }
    "titleEnabled" -> when {
      v is CollapsingToolbarLayout && arg is Boolean -> {
        v.setTitleEnabled(arg)
        true
      }
      else -> false
    }
    "backgroundTint" -> when {
      v is BottomAppBar && arg is ColorStateList? -> {
        v.setBackgroundTint(arg)
        true
      }
      else -> false
    }
    "cradleVerticalOffset" -> when {
      v is BottomAppBar && arg is Float -> {
        v.setCradleVerticalOffset(arg)
        true
      }
      else -> false
    }
    "fabAlignmentMode" -> when {
      v is BottomAppBar && arg is Int -> {
        v.setFabAlignmentMode(arg)
        true
      }
      else -> false
    }
    "fabAnimationMode" -> when {
      v is BottomAppBar && arg is Int -> {
        v.setFabAnimationMode(arg)
        true
      }
      else -> false
    }
    "fabCradleMargin" -> when {
      v is BottomAppBar && arg is Float -> {
        v.setFabCradleMargin(arg)
        true
      }
      else -> false
    }
    "fabCradleRoundedCornerRadius" -> when {
      v is BottomAppBar && arg is Float -> {
        v.setFabCradleRoundedCornerRadius(arg)
        true
      }
      else -> false
    }
    "hideOnScroll" -> when {
      v is BottomAppBar && arg is Boolean -> {
        v.setHideOnScroll(arg)
        true
      }
      else -> false
    }
    "itemBackground" -> when {
      v is BottomNavigationView && arg is Drawable? -> {
        v.setItemBackground(arg)
        true
      }
      v is NavigationView && arg is Drawable? -> {
        v.setItemBackground(arg)
        true
      }
      else -> false
    }
    "itemBackgroundResource" -> when {
      v is BottomNavigationView && arg is Int -> {
        v.setItemBackgroundResource(arg)
        true
      }
      v is NavigationView && arg is Int -> {
        v.setItemBackgroundResource(arg)
        true
      }
      else -> false
    }
    "itemHorizontalTranslationEnabled" -> when {
      v is BottomNavigationView && arg is Boolean -> {
        v.setItemHorizontalTranslationEnabled(arg)
        true
      }
      else -> false
    }
    "itemIconSize" -> when {
      v is BottomNavigationView && arg is Int -> {
        v.setItemIconSize(arg)
        true
      }
      v is NavigationView && arg is Int -> {
        v.setItemIconSize(arg)
        true
      }
      else -> false
    }
    "itemIconSizeRes" -> when {
      v is BottomNavigationView && arg is Int -> {
        v.setItemIconSizeRes(arg)
        true
      }
      else -> false
    }
    "itemIconTintList" -> when {
       v is BottomNavigationView && arg is Int? -> {
        if(arg != null) {
          v.setItemIconTintList(ResourcesCompat.getColorStateList(v.resources, arg, null))
        } else { 
          v.setItemIconTintList(null)
        }
        true
      }
       v is NavigationView && arg is Int? -> {
        if(arg != null) {
          v.setItemIconTintList(ResourcesCompat.getColorStateList(v.resources, arg, null))
        } else { 
          v.setItemIconTintList(null)
        }
        true
      }
      else -> false
    }
    "itemRippleColor" -> when {
       v is BottomNavigationView && arg is Int -> {
        v.setItemRippleColor(ColorStateList.valueOf(v.resources.getColor(arg)))
        true
      }
      else -> false
    }
    "itemTextAppearanceActive" -> when {
      v is BottomNavigationView && arg is Int -> {
        v.setItemTextAppearanceActive(arg)
        true
      }
      else -> false
    }
    "itemTextAppearanceInactive" -> when {
      v is BottomNavigationView && arg is Int -> {
        v.setItemTextAppearanceInactive(arg)
        true
      }
      else -> false
    }
    "itemTextColor" -> when {
       v is BottomNavigationView && arg is Int? -> {
        if(arg != null) {
          v.setItemTextColor(ResourcesCompat.getColorStateList(v.resources, arg, null))
        } else { 
          v.setItemTextColor(null)
        }
        true
      }
       v is NavigationView && arg is Int? -> {
        if(arg != null) {
          v.setItemTextColor(ResourcesCompat.getColorStateList(v.resources, arg, null))
        } else { 
          v.setItemTextColor(null)
        }
        true
      }
      else -> false
    }
    "labelVisibilityMode" -> when {
      v is BottomNavigationView && arg is Int -> {
        v.setLabelVisibilityMode(arg)
        true
      }
      else -> false
    }
    "onNavigationItemReselected" -> when {
      v is BottomNavigationView -> when {
        arg == null -> {
          v.setOnNavigationItemReselectedListener(null as?
              BottomNavigationView.OnNavigationItemReselectedListener?)
          true
        }
        arg is Function<*> -> {
          arg as ((arg0: MenuItem) -> Unit)?
          v.setOnNavigationItemReselectedListener { arg0 ->
            arg(arg0).also { Inkremental.render() }
          }
          true
        }
        else -> false
      }
      else -> false
    }
    "onNavigationItemSelected" -> when {
      v is BottomNavigationView -> when {
        arg == null -> {
          v.setOnNavigationItemSelectedListener(null as?
              BottomNavigationView.OnNavigationItemSelectedListener?)
          true
        }
        arg is Function<*> -> {
          arg as ((arg0: MenuItem) -> Boolean)?
          v.setOnNavigationItemSelectedListener { arg0 ->
            arg(arg0).also { Inkremental.render() }
          }
          true
        }
        else -> false
      }
      else -> false
    }
    "selectedItemId" -> when {
      v is BottomNavigationView && arg is Int -> {
        v.setSelectedItemId(arg)
        true
      }
      else -> false
    }
    "checkable" -> when {
      v is MaterialButton && arg is Boolean -> {
        v.setCheckable(arg)
        true
      }
      v is MaterialCardView && arg is Boolean -> {
        v.setCheckable(arg)
        true
      }
      v is Chip && arg is Boolean -> {
        v.setCheckable(arg)
        true
      }
      v is CheckableImageButton && arg is Boolean -> {
        v.setCheckable(arg)
        true
      }
      else -> false
    }
    "checked" -> when {
      v is MaterialButton && arg is Boolean -> {
        v.setChecked(arg)
        true
      }
      v is MaterialCardView && arg is Boolean -> {
        v.setChecked(arg)
        true
      }
      else -> false
    }
    "cornerRadius" -> when {
      v is MaterialButton && arg is Int -> {
        v.setCornerRadius(arg)
        true
      }
      else -> false
    }
    "cornerRadiusResource" -> when {
      v is MaterialButton && arg is Int -> {
        v.setCornerRadiusResource(arg)
        true
      }
      else -> false
    }
    "icon" -> when {
      v is MaterialButton && arg is Drawable? -> {
        v.setIcon(arg)
        true
      }
      else -> false
    }
    "iconGravity" -> when {
      v is MaterialButton && arg is Int -> {
        v.setIconGravity(arg)
        true
      }
      else -> false
    }
    "iconPadding" -> when {
      v is MaterialButton && arg is Int -> {
        v.setIconPadding(arg)
        true
      }
      else -> false
    }
    "iconResource" -> when {
      v is MaterialButton && arg is Int -> {
        v.setIconResource(arg)
        true
      }
      else -> false
    }
    "iconSize" -> when {
      v is MaterialButton && arg is Int -> {
        v.setIconSize(arg)
        true
      }
      v is NavigationMenuItemView && arg is Int -> {
        v.setIconSize(arg)
        true
      }
      else -> false
    }
    "iconTint" -> when {
      v is MaterialButton && arg is ColorStateList? -> {
        v.setIconTint(arg)
        true
      }
      else -> false
    }
    "iconTintMode" -> when {
      v is MaterialButton && arg is PorterDuff.Mode -> {
        v.setIconTintMode(arg)
        true
      }
      else -> false
    }
    "iconTintResource" -> when {
      v is MaterialButton && arg is Int -> {
        v.setIconTintResource(arg)
        true
      }
      else -> false
    }
    "rippleColor" -> when {
      v is MaterialButton && arg is ColorStateList? -> {
        v.setRippleColor(arg)
        true
      }
      v is MaterialCardView && arg is ColorStateList? -> {
        v.setRippleColor(arg)
        true
      }
      v is Chip && arg is ColorStateList? -> {
        v.setRippleColor(arg)
        true
      }
      v is FloatingActionButton && arg is ColorStateList? -> {
        v.setRippleColor(arg)
        true
      }
      v is FloatingActionButton && arg is Int -> {
        v.setRippleColor(arg)
        true
      }
      else -> false
    }
    "rippleColorResource" -> when {
      v is MaterialButton && arg is Int -> {
        v.setRippleColorResource(arg)
        true
      }
      v is MaterialCardView && arg is Int -> {
        v.setRippleColorResource(arg)
        true
      }
      v is Chip && arg is Int -> {
        v.setRippleColorResource(arg)
        true
      }
      else -> false
    }
    "shapeAppearanceModel" -> when {
      v is MaterialButton && arg is ShapeAppearanceModel -> {
        v.setShapeAppearanceModel(arg)
        true
      }
      v is MaterialCardView && arg is ShapeAppearanceModel -> {
        v.setShapeAppearanceModel(arg)
        true
      }
      v is Chip && arg is ShapeAppearanceModel -> {
        v.setShapeAppearanceModel(arg)
        true
      }
      v is FloatingActionButton && arg is ShapeAppearanceModel -> {
        v.setShapeAppearanceModel(arg)
        true
      }
      v is ShapeableImageView && arg is ShapeAppearanceModel -> {
        v.setShapeAppearanceModel(arg)
        true
      }
      else -> false
    }
    "strokeColor" -> when {
      v is MaterialButton && arg is ColorStateList? -> {
        v.setStrokeColor(arg)
        true
      }
      v is MaterialCardView && arg is ColorStateList -> {
        v.setStrokeColor(arg)
        true
      }
      v is ShapeableImageView && arg is ColorStateList? -> {
        v.setStrokeColor(arg)
        true
      }
      v is MaterialCardView && arg is Int -> {
        v.setStrokeColor(arg)
        true
      }
      else -> false
    }
    "strokeColorResource" -> when {
      v is MaterialButton && arg is Int -> {
        v.setStrokeColorResource(arg)
        true
      }
      v is ShapeableImageView && arg is Int -> {
        v.setStrokeColorResource(arg)
        true
      }
      else -> false
    }
    "strokeWidth" -> when {
      v is MaterialButton && arg is Int -> {
        v.setStrokeWidth(arg)
        true
      }
      v is MaterialCardView && arg is Int -> {
        v.setStrokeWidth(arg)
        true
      }
      v is ShapeableImageView && arg is Int -> {
        v.setStrokeWidth(arg)
        true
      }
      else -> false
    }
    "strokeWidthResource" -> when {
      v is MaterialButton && arg is Int -> {
        v.setStrokeWidthResource(arg)
        true
      }
      v is ShapeableImageView && arg is Int -> {
        v.setStrokeWidthResource(arg)
        true
      }
      else -> false
    }
    "selectionRequired" -> when {
      v is MaterialButtonToggleGroup && arg is Boolean -> {
        v.setSelectionRequired(arg)
        true
      }
      v is ChipGroup && arg is Boolean -> {
        v.setSelectionRequired(arg)
        true
      }
      else -> false
    }
    "singleSelection" -> when {
      v is MaterialButtonToggleGroup && arg is Boolean -> {
        v.setSingleSelection(arg)
        true
      }
      v is ChipGroup && arg is Boolean -> {
        v.setSingleSelection(arg)
        true
      }
      v is MaterialButtonToggleGroup && arg is Int -> {
        v.setSingleSelection(arg)
        true
      }
      v is ChipGroup && arg is Int -> {
        v.setSingleSelection(arg)
        true
      }
      else -> false
    }
    "checkedIcon" -> when {
      v is MaterialCardView && arg is Drawable? -> {
        v.setCheckedIcon(arg)
        true
      }
      v is Chip && arg is Drawable? -> {
        v.setCheckedIcon(arg)
        true
      }
      else -> false
    }
    "checkedIconResource" -> when {
      v is MaterialCardView && arg is Int -> {
        v.setCheckedIconResource(arg)
        true
      }
      v is Chip && arg is Int -> {
        v.setCheckedIconResource(arg)
        true
      }
      else -> false
    }
    "checkedIconTint" -> when {
      v is MaterialCardView && arg is ColorStateList? -> {
        v.setCheckedIconTint(arg)
        true
      }
      else -> false
    }
    "dragged" -> when {
      v is MaterialCardView && arg is Boolean -> {
        v.setDragged(arg)
        true
      }
      else -> false
    }
    "onCheckedChange" -> when {
      v is MaterialCardView -> when {
        arg == null -> {
          v.setOnCheckedChangeListener(null as? MaterialCardView.OnCheckedChangeListener?)
          true
        }
        arg is Function<*> -> {
          arg as ((arg0: MaterialCardView, arg1: Boolean) -> Unit)?
          v.setOnCheckedChangeListener { arg0, arg1 ->
            arg(arg0, arg1).also { Inkremental.render() }
          }
          true
        }
        else -> false
      }
      v is ChipGroup -> when {
        arg == null -> {
          v.setOnCheckedChangeListener(null as? ChipGroup.OnCheckedChangeListener?)
          true
        }
        arg is Function<*> -> {
          arg as ((arg0: ChipGroup, arg1: Int) -> Unit)?
          v.setOnCheckedChangeListener { arg0, arg1 ->
            arg(arg0, arg1).also { Inkremental.render() }
          }
          true
        }
        else -> false
      }
      else -> false
    }
    "progress" -> when {
      v is MaterialCardView && arg is Float -> {
        v.setProgress(arg)
        true
      }
      else -> false
    }
    "useMaterialThemeColors" -> when {
      v is MaterialCheckBox && arg is Boolean -> {
        v.setUseMaterialThemeColors(arg)
        true
      }
      v is MaterialRadioButton && arg is Boolean -> {
        v.setUseMaterialThemeColors(arg)
        true
      }
      v is SwitchMaterial && arg is Boolean -> {
        v.setUseMaterialThemeColors(arg)
        true
      }
      else -> false
    }
    "checkableResource" -> when {
      v is Chip && arg is Int -> {
        v.setCheckableResource(arg)
        true
      }
      else -> false
    }
    "checkedIconVisible" -> when {
      v is Chip && arg is Boolean -> {
        v.setCheckedIconVisible(arg)
        true
      }
      v is Chip && arg is Int -> {
        v.setCheckedIconVisible(arg)
        true
      }
      else -> false
    }
    "chipBackgroundColor" -> when {
      v is Chip && arg is ColorStateList? -> {
        v.setChipBackgroundColor(arg)
        true
      }
      else -> false
    }
    "chipBackgroundColorResource" -> when {
      v is Chip && arg is Int -> {
        v.setChipBackgroundColorResource(arg)
        true
      }
      else -> false
    }
    "chipDrawable" -> when {
      v is Chip && arg is ChipDrawable -> {
        v.setChipDrawable(arg)
        true
      }
      else -> false
    }
    "chipEndPadding" -> when {
      v is Chip && arg is Float -> {
        v.setChipEndPadding(arg)
        true
      }
      else -> false
    }
    "chipEndPaddingResource" -> when {
      v is Chip && arg is Int -> {
        v.setChipEndPaddingResource(arg)
        true
      }
      else -> false
    }
    "chipIcon" -> when {
      v is Chip && arg is Drawable? -> {
        v.setChipIcon(arg)
        true
      }
      else -> false
    }
    "chipIconResource" -> when {
      v is Chip && arg is Int -> {
        v.setChipIconResource(arg)
        true
      }
      else -> false
    }
    "chipIconSize" -> when {
      v is Chip && arg is Float -> {
        v.setChipIconSize(arg)
        true
      }
      else -> false
    }
    "chipIconSizeResource" -> when {
      v is Chip && arg is Int -> {
        v.setChipIconSizeResource(arg)
        true
      }
      else -> false
    }
    "chipIconTint" -> when {
      v is Chip && arg is ColorStateList? -> {
        v.setChipIconTint(arg)
        true
      }
      else -> false
    }
    "chipIconTintResource" -> when {
      v is Chip && arg is Int -> {
        v.setChipIconTintResource(arg)
        true
      }
      else -> false
    }
    "chipIconVisible" -> when {
      v is Chip && arg is Boolean -> {
        v.setChipIconVisible(arg)
        true
      }
      v is Chip && arg is Int -> {
        v.setChipIconVisible(arg)
        true
      }
      else -> false
    }
    "chipMinHeight" -> when {
      v is Chip && arg is Float -> {
        v.setChipMinHeight(arg)
        true
      }
      else -> false
    }
    "chipMinHeightResource" -> when {
      v is Chip && arg is Int -> {
        v.setChipMinHeightResource(arg)
        true
      }
      else -> false
    }
    "chipStartPadding" -> when {
      v is Chip && arg is Float -> {
        v.setChipStartPadding(arg)
        true
      }
      else -> false
    }
    "chipStartPaddingResource" -> when {
      v is Chip && arg is Int -> {
        v.setChipStartPaddingResource(arg)
        true
      }
      else -> false
    }
    "chipStrokeColor" -> when {
      v is Chip && arg is ColorStateList? -> {
        v.setChipStrokeColor(arg)
        true
      }
      else -> false
    }
    "chipStrokeColorResource" -> when {
      v is Chip && arg is Int -> {
        v.setChipStrokeColorResource(arg)
        true
      }
      else -> false
    }
    "chipStrokeWidth" -> when {
      v is Chip && arg is Float -> {
        v.setChipStrokeWidth(arg)
        true
      }
      else -> false
    }
    "chipStrokeWidthResource" -> when {
      v is Chip && arg is Int -> {
        v.setChipStrokeWidthResource(arg)
        true
      }
      else -> false
    }
    "closeIcon" -> when {
      v is Chip && arg is Drawable? -> {
        v.setCloseIcon(arg)
        true
      }
      else -> false
    }
    "closeIconContentDescription" -> when {
      v is Chip && arg is CharSequence? -> {
        v.setCloseIconContentDescription(arg)
        true
      }
      else -> false
    }
    "closeIconEndPadding" -> when {
      v is Chip && arg is Float -> {
        v.setCloseIconEndPadding(arg)
        true
      }
      else -> false
    }
    "closeIconEndPaddingResource" -> when {
      v is Chip && arg is Int -> {
        v.setCloseIconEndPaddingResource(arg)
        true
      }
      else -> false
    }
    "closeIconResource" -> when {
      v is Chip && arg is Int -> {
        v.setCloseIconResource(arg)
        true
      }
      else -> false
    }
    "closeIconSize" -> when {
      v is Chip && arg is Float -> {
        v.setCloseIconSize(arg)
        true
      }
      else -> false
    }
    "closeIconSizeResource" -> when {
      v is Chip && arg is Int -> {
        v.setCloseIconSizeResource(arg)
        true
      }
      else -> false
    }
    "closeIconStartPadding" -> when {
      v is Chip && arg is Float -> {
        v.setCloseIconStartPadding(arg)
        true
      }
      else -> false
    }
    "closeIconStartPaddingResource" -> when {
      v is Chip && arg is Int -> {
        v.setCloseIconStartPaddingResource(arg)
        true
      }
      else -> false
    }
    "closeIconTint" -> when {
      v is Chip && arg is ColorStateList? -> {
        v.setCloseIconTint(arg)
        true
      }
      else -> false
    }
    "closeIconTintResource" -> when {
      v is Chip && arg is Int -> {
        v.setCloseIconTintResource(arg)
        true
      }
      else -> false
    }
    "closeIconVisible" -> when {
      v is Chip && arg is Boolean -> {
        v.setCloseIconVisible(arg)
        true
      }
      v is Chip && arg is Int -> {
        v.setCloseIconVisible(arg)
        true
      }
      else -> false
    }
    "ensureMinTouchTargetSize" -> when {
      v is Chip && arg is Boolean -> {
        v.setEnsureMinTouchTargetSize(arg)
        true
      }
      v is FloatingActionButton && arg is Boolean -> {
        v.setEnsureMinTouchTargetSize(arg)
        true
      }
      else -> false
    }
    "hideMotionSpec" -> when {
      v is Chip && arg is MotionSpec? -> {
        v.setHideMotionSpec(arg)
        true
      }
      v is ExtendedFloatingActionButton && arg is MotionSpec? -> {
        v.setHideMotionSpec(arg)
        true
      }
      v is FloatingActionButton && arg is MotionSpec? -> {
        v.setHideMotionSpec(arg)
        true
      }
      else -> false
    }
    "hideMotionSpecResource" -> when {
      v is Chip && arg is Int -> {
        v.setHideMotionSpecResource(arg)
        true
      }
      v is ExtendedFloatingActionButton && arg is Int -> {
        v.setHideMotionSpecResource(arg)
        true
      }
      v is FloatingActionButton && arg is Int -> {
        v.setHideMotionSpecResource(arg)
        true
      }
      else -> false
    }
    "iconEndPadding" -> when {
      v is Chip && arg is Float -> {
        v.setIconEndPadding(arg)
        true
      }
      else -> false
    }
    "iconEndPaddingResource" -> when {
      v is Chip && arg is Int -> {
        v.setIconEndPaddingResource(arg)
        true
      }
      else -> false
    }
    "iconStartPadding" -> when {
      v is Chip && arg is Float -> {
        v.setIconStartPadding(arg)
        true
      }
      else -> false
    }
    "iconStartPaddingResource" -> when {
      v is Chip && arg is Int -> {
        v.setIconStartPaddingResource(arg)
        true
      }
      else -> false
    }
    "onCloseIconClick" -> when {
      v is Chip -> when {
        arg == null -> {
          v.setOnCloseIconClickListener(null as? View.OnClickListener?)
          true
        }
        arg is Function<*> -> {
          arg as ((arg0: View) -> Unit)?
          v.setOnCloseIconClickListener { arg0 ->
            arg(arg0).also { Inkremental.render() }
          }
          true
        }
        else -> false
      }
      else -> false
    }
    "showMotionSpec" -> when {
      v is Chip && arg is MotionSpec? -> {
        v.setShowMotionSpec(arg)
        true
      }
      v is ExtendedFloatingActionButton && arg is MotionSpec? -> {
        v.setShowMotionSpec(arg)
        true
      }
      v is FloatingActionButton && arg is MotionSpec? -> {
        v.setShowMotionSpec(arg)
        true
      }
      else -> false
    }
    "showMotionSpecResource" -> when {
      v is Chip && arg is Int -> {
        v.setShowMotionSpecResource(arg)
        true
      }
      v is ExtendedFloatingActionButton && arg is Int -> {
        v.setShowMotionSpecResource(arg)
        true
      }
      v is FloatingActionButton && arg is Int -> {
        v.setShowMotionSpecResource(arg)
        true
      }
      else -> false
    }
    "textAppearance" -> when {
      v is Chip && arg is TextAppearance? -> {
        v.setTextAppearance(arg)
        true
      }
      v is NavigationMenuItemView && arg is Int -> {
        v.setTextAppearance(arg)
        true
      }
      else -> false
    }
    "textAppearanceResource" -> when {
      v is Chip && arg is Int -> {
        v.setTextAppearanceResource(arg)
        true
      }
      else -> false
    }
    "textEndPadding" -> when {
      v is Chip && arg is Float -> {
        v.setTextEndPadding(arg)
        true
      }
      else -> false
    }
    "textEndPaddingResource" -> when {
      v is Chip && arg is Int -> {
        v.setTextEndPaddingResource(arg)
        true
      }
      else -> false
    }
    "textStartPadding" -> when {
      v is Chip && arg is Float -> {
        v.setTextStartPadding(arg)
        true
      }
      else -> false
    }
    "textStartPaddingResource" -> when {
      v is Chip && arg is Int -> {
        v.setTextStartPaddingResource(arg)
        true
      }
      else -> false
    }
    "chipSpacing" -> when {
      v is ChipGroup && arg is Int -> {
        v.setChipSpacing(arg)
        true
      }
      else -> false
    }
    "chipSpacingHorizontal" -> when {
      v is ChipGroup && arg is Int -> {
        v.setChipSpacingHorizontal(arg)
        true
      }
      else -> false
    }
    "chipSpacingHorizontalResource" -> when {
      v is ChipGroup && arg is Int -> {
        v.setChipSpacingHorizontalResource(arg)
        true
      }
      else -> false
    }
    "chipSpacingResource" -> when {
      v is ChipGroup && arg is Int -> {
        v.setChipSpacingResource(arg)
        true
      }
      else -> false
    }
    "chipSpacingVertical" -> when {
      v is ChipGroup && arg is Int -> {
        v.setChipSpacingVertical(arg)
        true
      }
      else -> false
    }
    "chipSpacingVerticalResource" -> when {
      v is ChipGroup && arg is Int -> {
        v.setChipSpacingVerticalResource(arg)
        true
      }
      else -> false
    }
    "singleLine" -> when {
      v is FlowLayout && arg is Boolean -> {
        v.setSingleLine(arg)
        true
      }
      v is ChipGroup && arg is Int -> {
        v.setSingleLine(arg)
        true
      }
      else -> false
    }
    "circularRevealOverlayDrawable" -> when {
      v is CircularRevealFrameLayout && arg is Drawable? -> {
        v.setCircularRevealOverlayDrawable(arg)
        true
      }
      v is CircularRevealGridLayout && arg is Drawable? -> {
        v.setCircularRevealOverlayDrawable(arg)
        true
      }
      v is CircularRevealLinearLayout && arg is Drawable? -> {
        v.setCircularRevealOverlayDrawable(arg)
        true
      }
      v is CircularRevealRelativeLayout && arg is Drawable? -> {
        v.setCircularRevealOverlayDrawable(arg)
        true
      }
      v is CircularRevealCardView && arg is Drawable? -> {
        v.setCircularRevealOverlayDrawable(arg)
        true
      }
      else -> false
    }
    "circularRevealScrimColor" -> when {
      v is CircularRevealFrameLayout && arg is Int -> {
        v.setCircularRevealScrimColor(arg)
        true
      }
      v is CircularRevealGridLayout && arg is Int -> {
        v.setCircularRevealScrimColor(arg)
        true
      }
      v is CircularRevealLinearLayout && arg is Int -> {
        v.setCircularRevealScrimColor(arg)
        true
      }
      v is CircularRevealRelativeLayout && arg is Int -> {
        v.setCircularRevealScrimColor(arg)
        true
      }
      v is CircularRevealCardView && arg is Int -> {
        v.setCircularRevealScrimColor(arg)
        true
      }
      else -> false
    }
    "revealInfo" -> when {
      v is CircularRevealFrameLayout && arg is CircularRevealWidget.RevealInfo? -> {
        v.setRevealInfo(arg)
        true
      }
      v is CircularRevealGridLayout && arg is CircularRevealWidget.RevealInfo? -> {
        v.setRevealInfo(arg)
        true
      }
      v is CircularRevealLinearLayout && arg is CircularRevealWidget.RevealInfo? -> {
        v.setRevealInfo(arg)
        true
      }
      v is CircularRevealRelativeLayout && arg is CircularRevealWidget.RevealInfo? -> {
        v.setRevealInfo(arg)
        true
      }
      v is CircularRevealCardView && arg is CircularRevealWidget.RevealInfo? -> {
        v.setRevealInfo(arg)
        true
      }
      else -> false
    }
    "extendMotionSpec" -> when {
      v is ExtendedFloatingActionButton && arg is MotionSpec? -> {
        v.setExtendMotionSpec(arg)
        true
      }
      else -> false
    }
    "extendMotionSpecResource" -> when {
      v is ExtendedFloatingActionButton && arg is Int -> {
        v.setExtendMotionSpecResource(arg)
        true
      }
      else -> false
    }
    "extended" -> when {
      v is ExtendedFloatingActionButton && arg is Boolean -> {
        v.setExtended(arg)
        true
      }
      else -> false
    }
    "shrinkMotionSpec" -> when {
      v is ExtendedFloatingActionButton && arg is MotionSpec? -> {
        v.setShrinkMotionSpec(arg)
        true
      }
      else -> false
    }
    "shrinkMotionSpecResource" -> when {
      v is ExtendedFloatingActionButton && arg is Int -> {
        v.setShrinkMotionSpecResource(arg)
        true
      }
      else -> false
    }
    "compatElevation" -> when {
      v is FloatingActionButton && arg is Int -> {
        v.setCompatElevation(dip(arg).toFloat())
        true
      }
      else -> false
    }
    "compatElevationResource" -> when {
      v is FloatingActionButton && arg is Int -> {
        v.setCompatElevationResource(arg)
        true
      }
      else -> false
    }
    "compatHoveredFocusedTranslationZ" -> when {
      v is FloatingActionButton && arg is Float -> {
        v.setCompatHoveredFocusedTranslationZ(arg)
        true
      }
      else -> false
    }
    "compatHoveredFocusedTranslationZResource" -> when {
      v is FloatingActionButton && arg is Int -> {
        v.setCompatHoveredFocusedTranslationZResource(arg)
        true
      }
      else -> false
    }
    "compatPressedTranslationZ" -> when {
      v is FloatingActionButton && arg is Float -> {
        v.setCompatPressedTranslationZ(arg)
        true
      }
      else -> false
    }
    "compatPressedTranslationZResource" -> when {
      v is FloatingActionButton && arg is Int -> {
        v.setCompatPressedTranslationZResource(arg)
        true
      }
      else -> false
    }
    "customSize" -> when {
      v is FloatingActionButton && arg is Int -> {
        v.setCustomSize(arg)
        true
      }
      else -> false
    }
    "expandedComponentIdHint" -> when {
      v is FloatingActionButton && arg is Int -> {
        v.setExpandedComponentIdHint(arg)
        true
      }
      else -> false
    }
    "shadowPaddingEnabled" -> when {
      v is FloatingActionButton && arg is Boolean -> {
        v.setShadowPaddingEnabled(arg)
        true
      }
      else -> false
    }
    "size" -> when {
      v is FloatingActionButton && arg is Int -> {
        v.setSize(arg)
        true
      }
      else -> false
    }
    "supportBackgroundTintList" -> when {
      v is FloatingActionButton && arg is ColorStateList? -> {
        v.setSupportBackgroundTintList(arg)
        true
      }
      else -> false
    }
    "supportBackgroundTintMode" -> when {
      v is FloatingActionButton && arg is PorterDuff.Mode? -> {
        v.setSupportBackgroundTintMode(arg)
        true
      }
      else -> false
    }
    "supportImageTintList" -> when {
      v is FloatingActionButton && arg is ColorStateList? -> {
        v.setSupportImageTintList(arg)
        true
      }
      else -> false
    }
    "supportImageTintMode" -> when {
      v is FloatingActionButton && arg is PorterDuff.Mode? -> {
        v.setSupportImageTintMode(arg)
        true
      }
      else -> false
    }
    "useCompatPadding" -> when {
      v is FloatingActionButton && arg is Boolean -> {
        v.setUseCompatPadding(arg)
        true
      }
      else -> false
    }
    "pressable" -> when {
      v is CheckableImageButton && arg is Boolean -> {
        v.setPressable(arg)
        true
      }
      else -> false
    }
    "horizontalPadding" -> when {
      v is NavigationMenuItemView && arg is Int -> {
        v.setHorizontalPadding(arg)
        true
      }
      else -> false
    }
    "maxLines" -> when {
      v is NavigationMenuItemView && arg is Int -> {
        v.setMaxLines(arg)
        true
      }
      else -> false
    }
    "needsEmptyIcon" -> when {
      v is NavigationMenuItemView && arg is Boolean -> {
        v.setNeedsEmptyIcon(arg)
        true
      }
      else -> false
    }
    "drawBottomInsetForeground" -> when {
      v is ScrimInsetsFrameLayout && arg is Boolean -> {
        v.setDrawBottomInsetForeground(arg)
        true
      }
      else -> false
    }
    "drawTopInsetForeground" -> when {
      v is ScrimInsetsFrameLayout && arg is Boolean -> {
        v.setDrawTopInsetForeground(arg)
        true
      }
      else -> false
    }
    "scrimInsetForeground" -> when {
      v is ScrimInsetsFrameLayout && arg is Drawable? -> {
        v.setScrimInsetForeground(arg)
        true
      }
      else -> false
    }
    "checkedItem" -> when {
      v is NavigationView && arg is MenuItem -> {
        v.setCheckedItem(arg)
        true
      }
      v is NavigationView && arg is Int -> {
        v.setCheckedItem(arg)
        true
      }
      else -> false
    }
    "itemHorizontalPadding" -> when {
      v is NavigationView && arg is Int -> {
        v.setItemHorizontalPadding(arg)
        true
      }
      else -> false
    }
    "itemHorizontalPaddingResource" -> when {
      v is NavigationView && arg is Int -> {
        v.setItemHorizontalPaddingResource(arg)
        true
      }
      else -> false
    }
    "itemIconPadding" -> when {
      v is NavigationView && arg is Int -> {
        v.setItemIconPadding(arg)
        true
      }
      else -> false
    }
    "itemIconPaddingResource" -> when {
      v is NavigationView && arg is Int -> {
        v.setItemIconPaddingResource(arg)
        true
      }
      else -> false
    }
    "itemMaxLines" -> when {
      v is NavigationView && arg is Int -> {
        v.setItemMaxLines(arg)
        true
      }
      else -> false
    }
    "itemTextAppearance" -> when {
      v is NavigationView && arg is Int -> {
        v.setItemTextAppearance(arg)
        true
      }
      else -> false
    }
    "navigationItemSelectedListener" -> when {
      v is NavigationView && arg is NavigationView.OnNavigationItemSelectedListener? -> {
        v.setNavigationItemSelectedListener(arg)
        true
      }
      else -> false
    }
    "haloColor" -> when {
      v is Slider && arg is ColorStateList -> {
        v.setHaloColor(arg)
        true
      }
      else -> false
    }
    "haloRadius" -> when {
      v is Slider && arg is Int -> {
        v.setHaloRadius(arg)
        true
      }
      else -> false
    }
    "haloRadiusResource" -> when {
      v is Slider && arg is Int -> {
        v.setHaloRadiusResource(arg)
        true
      }
      else -> false
    }
    "labelBehavior" -> when {
      v is Slider && arg is Int -> {
        v.setLabelBehavior(arg)
        true
      }
      else -> false
    }
    "labelFormatter" -> when {
      v is Slider && arg is Slider.LabelFormatter? -> {
        v.setLabelFormatter(arg)
        true
      }
      else -> false
    }
    "stepSize" -> when {
      v is Slider && arg is Float -> {
        v.setStepSize(arg)
        true
      }
      else -> false
    }
    "thumbColor" -> when {
      v is Slider && arg is ColorStateList -> {
        v.setThumbColor(arg)
        true
      }
      else -> false
    }
    "thumbElevation" -> when {
      v is Slider && arg is Int -> {
        v.setThumbElevation(dip(arg).toFloat())
        true
      }
      else -> false
    }
    "thumbElevationResource" -> when {
      v is Slider && arg is Int -> {
        v.setThumbElevationResource(arg)
        true
      }
      else -> false
    }
    "thumbRadius" -> when {
      v is Slider && arg is Int -> {
        v.setThumbRadius(arg)
        true
      }
      else -> false
    }
    "thumbRadiusResource" -> when {
      v is Slider && arg is Int -> {
        v.setThumbRadiusResource(arg)
        true
      }
      else -> false
    }
    "tickColor" -> when {
      v is Slider && arg is ColorStateList -> {
        v.setTickColor(arg)
        true
      }
      else -> false
    }
    "tickColorActive" -> when {
      v is Slider && arg is ColorStateList -> {
        v.setTickColorActive(arg)
        true
      }
      else -> false
    }
    "tickColorInactive" -> when {
      v is Slider && arg is ColorStateList -> {
        v.setTickColorInactive(arg)
        true
      }
      else -> false
    }
    "trackColor" -> when {
      v is Slider && arg is ColorStateList -> {
        v.setTrackColor(arg)
        true
      }
      else -> false
    }
    "trackColorActive" -> when {
      v is Slider && arg is ColorStateList -> {
        v.setTrackColorActive(arg)
        true
      }
      else -> false
    }
    "trackColorInactive" -> when {
      v is Slider && arg is ColorStateList -> {
        v.setTrackColorInactive(arg)
        true
      }
      else -> false
    }
    "trackHeight" -> when {
      v is Slider && arg is Int -> {
        v.setTrackHeight(arg)
        true
      }
      else -> false
    }
    "value" -> when {
      v is Slider && arg is Float -> {
        v.setValue(arg)
        true
      }
      else -> false
    }
    "valueFrom" -> when {
      v is Slider && arg is Float -> {
        v.setValueFrom(arg)
        true
      }
      else -> false
    }
    "valueTo" -> when {
      v is Slider && arg is Float -> {
        v.setValueTo(arg)
        true
      }
      else -> false
    }
    "inlineLabel" -> when {
      v is TabLayout && arg is Boolean -> {
        v.setInlineLabel(arg)
        true
      }
      else -> false
    }
    "inlineLabelResource" -> when {
      v is TabLayout && arg is Int -> {
        v.setInlineLabelResource(arg)
        true
      }
      else -> false
    }
    "selectedTabIndicator" -> when {
      v is TabLayout && arg is Drawable? -> {
        v.setSelectedTabIndicator(arg)
        true
      }
      v is TabLayout && arg is Int -> {
        v.setSelectedTabIndicator(arg)
        true
      }
      else -> false
    }
    "selectedTabIndicatorColor" -> when {
      v is TabLayout && arg is Int -> {
        v.setSelectedTabIndicatorColor(arg)
        true
      }
      else -> false
    }
    "selectedTabIndicatorGravity" -> when {
      v is TabLayout && arg is Int -> {
        v.setSelectedTabIndicatorGravity(arg)
        true
      }
      else -> false
    }
    "tabGravity" -> when {
      v is TabLayout && arg is Int -> {
        v.setTabGravity(arg)
        true
      }
      else -> false
    }
    "tabIconTint" -> when {
       v is TabLayout && arg is Int? -> {
        if(arg != null) {
          v.setTabIconTint(ResourcesCompat.getColorStateList(v.resources, arg, null))
        } else { 
          v.setTabIconTint(null)
        }
        true
      }
      else -> false
    }
    "tabIconTintResource" -> when {
      v is TabLayout && arg is Int -> {
        v.setTabIconTintResource(arg)
        true
      }
      else -> false
    }
    "tabIndicatorFullWidth" -> when {
      v is TabLayout && arg is Boolean -> {
        v.setTabIndicatorFullWidth(arg)
        true
      }
      else -> false
    }
    "tabMode" -> when {
      v is TabLayout && arg is Int -> {
        v.setTabMode(arg)
        true
      }
      else -> false
    }
    "tabRippleColor" -> when {
       v is TabLayout && arg is Int -> {
        v.setTabRippleColor(ColorStateList.valueOf(v.resources.getColor(arg)))
        true
      }
      else -> false
    }
    "tabRippleColorResource" -> when {
      v is TabLayout && arg is Int -> {
        v.setTabRippleColorResource(arg)
        true
      }
      else -> false
    }
    "tabTextColors" -> when {
       v is TabLayout && arg is Int? -> {
        if(arg != null) {
          v.setTabTextColors(ResourcesCompat.getColorStateList(v.resources, arg, null))
        } else { 
          v.setTabTextColors(null)
        }
        true
      }
      else -> false
    }
    "unboundedRipple" -> when {
      v is TabLayout && arg is Boolean -> {
        v.setUnboundedRipple(arg)
        true
      }
      else -> false
    }
    "unboundedRippleResource" -> when {
      v is TabLayout && arg is Int -> {
        v.setUnboundedRippleResource(arg)
        true
      }
      else -> false
    }
    "boxBackgroundColor" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setBoxBackgroundColor(arg)
        true
      }
      else -> false
    }
    "boxBackgroundColorResource" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setBoxBackgroundColorResource(arg)
        true
      }
      else -> false
    }
    "boxBackgroundMode" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setBoxBackgroundMode(arg)
        true
      }
      else -> false
    }
    "boxStrokeColor" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setBoxStrokeColor(arg)
        true
      }
      else -> false
    }
    "boxStrokeColorStateList" -> when {
      v is TextInputLayout && arg is ColorStateList -> {
        v.setBoxStrokeColorStateList(arg)
        true
      }
      else -> false
    }
    "boxStrokeErrorColor" -> when {
      v is TextInputLayout && arg is ColorStateList? -> {
        v.setBoxStrokeErrorColor(arg)
        true
      }
      else -> false
    }
    "counterEnabled" -> when {
      v is TextInputLayout && arg is Boolean -> {
        v.setCounterEnabled(arg)
        true
      }
      else -> false
    }
    "counterMaxLength" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setCounterMaxLength(arg)
        true
      }
      else -> false
    }
    "counterOverflowTextAppearance" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setCounterOverflowTextAppearance(arg)
        true
      }
      else -> false
    }
    "counterOverflowTextColor" -> when {
      v is TextInputLayout && arg is ColorStateList? -> {
        v.setCounterOverflowTextColor(arg)
        true
      }
      else -> false
    }
    "counterTextAppearance" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setCounterTextAppearance(arg)
        true
      }
      else -> false
    }
    "counterTextColor" -> when {
      v is TextInputLayout && arg is ColorStateList? -> {
        v.setCounterTextColor(arg)
        true
      }
      else -> false
    }
    "defaultHintTextColor" -> when {
      v is TextInputLayout && arg is ColorStateList? -> {
        v.setDefaultHintTextColor(arg)
        true
      }
      else -> false
    }
    "endIconActivated" -> when {
      v is TextInputLayout && arg is Boolean -> {
        v.setEndIconActivated(arg)
        true
      }
      else -> false
    }
    "endIconCheckable" -> when {
      v is TextInputLayout && arg is Boolean -> {
        v.setEndIconCheckable(arg)
        true
      }
      else -> false
    }
    "endIconContentDescription" -> when {
      v is TextInputLayout && arg is CharSequence? -> {
        v.setEndIconContentDescription(arg)
        true
      }
      v is TextInputLayout && arg is Int -> {
        v.setEndIconContentDescription(arg)
        true
      }
      else -> false
    }
    "endIconDrawable" -> when {
      v is TextInputLayout && arg is Drawable? -> {
        v.setEndIconDrawable(arg)
        true
      }
      v is TextInputLayout && arg is Int -> {
        v.setEndIconDrawable(arg)
        true
      }
      else -> false
    }
    "endIconMode" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setEndIconMode(arg)
        true
      }
      else -> false
    }
    "endIconOnClickListener" -> when {
      v is TextInputLayout && arg is View.OnClickListener? -> {
        v.setEndIconOnClickListener(arg)
        true
      }
      else -> false
    }
    "endIconOnLongClickListener" -> when {
      v is TextInputLayout && arg is View.OnLongClickListener? -> {
        v.setEndIconOnLongClickListener(arg)
        true
      }
      else -> false
    }
    "endIconTintList" -> when {
      v is TextInputLayout && arg is ColorStateList? -> {
        v.setEndIconTintList(arg)
        true
      }
      else -> false
    }
    "endIconTintMode" -> when {
      v is TextInputLayout && arg is PorterDuff.Mode? -> {
        v.setEndIconTintMode(arg)
        true
      }
      else -> false
    }
    "endIconVisible" -> when {
      v is TextInputLayout && arg is Boolean -> {
        v.setEndIconVisible(arg)
        true
      }
      else -> false
    }
    "error" -> when {
      v is TextInputLayout && arg is CharSequence? -> {
        v.setError(arg)
        true
      }
      else -> false
    }
    "errorContentDescription" -> when {
      v is TextInputLayout && arg is CharSequence? -> {
        v.setErrorContentDescription(arg)
        true
      }
      else -> false
    }
    "errorEnabled" -> when {
      v is TextInputLayout && arg is Boolean -> {
        v.setErrorEnabled(arg)
        true
      }
      else -> false
    }
    "errorIconDrawable" -> when {
      v is TextInputLayout && arg is Drawable? -> {
        v.setErrorIconDrawable(arg)
        true
      }
      v is TextInputLayout && arg is Int -> {
        v.setErrorIconDrawable(arg)
        true
      }
      else -> false
    }
    "errorIconTintList" -> when {
      v is TextInputLayout && arg is ColorStateList -> {
        v.setErrorIconTintList(arg)
        true
      }
      else -> false
    }
    "errorIconTintMode" -> when {
      v is TextInputLayout && arg is PorterDuff.Mode -> {
        v.setErrorIconTintMode(arg)
        true
      }
      else -> false
    }
    "errorTextAppearance" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setErrorTextAppearance(arg)
        true
      }
      else -> false
    }
    "errorTextColor" -> when {
      v is TextInputLayout && arg is ColorStateList? -> {
        v.setErrorTextColor(arg)
        true
      }
      else -> false
    }
    "helperText" -> when {
      v is TextInputLayout && arg is CharSequence? -> {
        v.setHelperText(arg)
        true
      }
      else -> false
    }
    "helperTextColor" -> when {
      v is TextInputLayout && arg is ColorStateList? -> {
        v.setHelperTextColor(arg)
        true
      }
      else -> false
    }
    "helperTextEnabled" -> when {
      v is TextInputLayout && arg is Boolean -> {
        v.setHelperTextEnabled(arg)
        true
      }
      else -> false
    }
    "helperTextTextAppearance" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setHelperTextTextAppearance(arg)
        true
      }
      else -> false
    }
    "hint" -> when {
      v is TextInputLayout && arg is CharSequence? -> {
        v.setHint(arg)
        true
      }
      else -> false
    }
    "hintAnimationEnabled" -> when {
      v is TextInputLayout && arg is Boolean -> {
        v.setHintAnimationEnabled(arg)
        true
      }
      else -> false
    }
    "hintEnabled" -> when {
      v is TextInputLayout && arg is Boolean -> {
        v.setHintEnabled(arg)
        true
      }
      else -> false
    }
    "hintTextAppearance" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setHintTextAppearance(arg)
        true
      }
      else -> false
    }
    "hintTextColor" -> when {
      v is TextInputLayout && arg is ColorStateList? -> {
        v.setHintTextColor(arg)
        true
      }
      else -> false
    }
    "placeholderText" -> when {
      v is TextInputLayout && arg is CharSequence? -> {
        v.setPlaceholderText(arg)
        true
      }
      else -> false
    }
    "placeholderTextAppearance" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setPlaceholderTextAppearance(arg)
        true
      }
      else -> false
    }
    "placeholderTextColor" -> when {
      v is TextInputLayout && arg is ColorStateList? -> {
        v.setPlaceholderTextColor(arg)
        true
      }
      else -> false
    }
    "prefixText" -> when {
      v is TextInputLayout && arg is CharSequence? -> {
        v.setPrefixText(arg)
        true
      }
      else -> false
    }
    "prefixTextAppearance" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setPrefixTextAppearance(arg)
        true
      }
      else -> false
    }
    "prefixTextColor" -> when {
      v is TextInputLayout && arg is ColorStateList -> {
        v.setPrefixTextColor(arg)
        true
      }
      else -> false
    }
    "startIconCheckable" -> when {
      v is TextInputLayout && arg is Boolean -> {
        v.setStartIconCheckable(arg)
        true
      }
      else -> false
    }
    "startIconContentDescription" -> when {
      v is TextInputLayout && arg is CharSequence? -> {
        v.setStartIconContentDescription(arg)
        true
      }
      v is TextInputLayout && arg is Int -> {
        v.setStartIconContentDescription(arg)
        true
      }
      else -> false
    }
    "startIconDrawable" -> when {
      v is TextInputLayout && arg is Drawable? -> {
        v.setStartIconDrawable(arg)
        true
      }
      v is TextInputLayout && arg is Int -> {
        v.setStartIconDrawable(arg)
        true
      }
      else -> false
    }
    "startIconOnClickListener" -> when {
      v is TextInputLayout && arg is View.OnClickListener? -> {
        v.setStartIconOnClickListener(arg)
        true
      }
      else -> false
    }
    "startIconOnLongClickListener" -> when {
      v is TextInputLayout && arg is View.OnLongClickListener? -> {
        v.setStartIconOnLongClickListener(arg)
        true
      }
      else -> false
    }
    "startIconTintList" -> when {
      v is TextInputLayout && arg is ColorStateList? -> {
        v.setStartIconTintList(arg)
        true
      }
      else -> false
    }
    "startIconTintMode" -> when {
      v is TextInputLayout && arg is PorterDuff.Mode? -> {
        v.setStartIconTintMode(arg)
        true
      }
      else -> false
    }
    "startIconVisible" -> when {
      v is TextInputLayout && arg is Boolean -> {
        v.setStartIconVisible(arg)
        true
      }
      else -> false
    }
    "suffixText" -> when {
      v is TextInputLayout && arg is CharSequence? -> {
        v.setSuffixText(arg)
        true
      }
      else -> false
    }
    "suffixTextAppearance" -> when {
      v is TextInputLayout && arg is Int -> {
        v.setSuffixTextAppearance(arg)
        true
      }
      else -> false
    }
    "suffixTextColor" -> when {
      v is TextInputLayout && arg is ColorStateList -> {
        v.setSuffixTextColor(arg)
        true
      }
      else -> false
    }
    "textInputAccessibilityDelegate" -> when {
      v is TextInputLayout && arg is TextInputLayout.AccessibilityDelegate? -> {
        v.setTextInputAccessibilityDelegate(arg)
        true
      }
      else -> false
    }
    "typeface" -> when {
      v is TextInputLayout && arg is Typeface? -> {
        v.setTypeface(arg)
        true
      }
      else -> false
    }
    else -> false
  }
}
