@file:Suppress("DEPRECATION", "UNCHECKED_CAST", "MemberVisibilityCanBePrivate", "unused")

package dev.inkremental.dsl.androidx.cardview

import android.content.res.ColorStateList
import android.view.View
import androidx.cardview.widget.CardView
import dev.inkremental.Inkremental
import kotlin.Any
import kotlin.Boolean
import kotlin.Float
import kotlin.Int
import kotlin.String
import kotlin.Suppress

/**
 * DSL for creating views and settings their attributes.
 * This file has been generated by
 * {@code gradle CardViewv7Setter}
 * It contains views and their setters for the library cardview-v7.
 * Please, don't edit it manually unless for debugging.
 */
object CardViewv7Setter : Inkremental.AttributeSetter<Any> {
  override fun set(
    v: View,
    name: String,
    arg: Any?,
    old: Any?
  ): Boolean = when (name) {
    "cardBackgroundColor" -> when {
      v is CardView && arg is ColorStateList? -> {
        v.setCardBackgroundColor(arg as ColorStateList)
        true
      }
      v is CardView && arg is Int -> {
        v.setCardBackgroundColor(arg)
        true
      }
      else -> false
    }
    "cardElevation" -> when {
      v is CardView && arg is Float -> {
        v.setCardElevation(arg)
        true
      }
      else -> false
    }
    "maxCardElevation" -> when {
      v is CardView && arg is Float -> {
        v.setMaxCardElevation(arg)
        true
      }
      else -> false
    }
    "preventCornerOverlap" -> when {
      v is CardView && arg is Boolean -> {
        v.setPreventCornerOverlap(arg)
        true
      }
      else -> false
    }
    "radius" -> when {
      v is CardView && arg is Float -> {
        v.setRadius(arg)
        true
      }
      else -> false
    }
    "useCompatPadding" -> when {
      v is CardView && arg is Boolean -> {
        v.setUseCompatPadding(arg)
        true
      }
      else -> false
    }
    else -> false
  }
}
