@file:Suppress("DEPRECATION", "UNCHECKED_CAST", "MemberVisibilityCanBePrivate", "unused")

package dev.inkremental.dsl.androidx.gridlayout

import android.util.Printer
import android.view.View
import androidx.gridlayout.widget.GridLayout
import dev.inkremental.Inkremental
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.Suppress

/**
 * DSL for creating views and settings their attributes.
 * This file has been generated by
 * {@code gradle GridlayoutV7Setter}
 * It contains views and their setters for the library gridlayout-v7-1.0.0.
 * Please, don't edit it manually unless for debugging.
 */
object GridlayoutV7Setter : Inkremental.AttributeSetter<Any> {
  override fun set(
    v: View,
    name: String,
    arg: Any?,
    old: Any?
  ): Boolean = when (name) {
    "alignmentMode" -> when {
      v is GridLayout && arg is Int -> {
        v.setAlignmentMode(arg)
        true
      }
      else -> false
    }
    "columnCount" -> when {
      v is GridLayout && arg is Int -> {
        v.setColumnCount(arg)
        true
      }
      else -> false
    }
    "columnOrderPreserved" -> when {
      v is GridLayout && arg is Boolean -> {
        v.setColumnOrderPreserved(arg)
        true
      }
      else -> false
    }
    "orientation" -> when {
      v is GridLayout && arg is Int -> {
        v.setOrientation(arg)
        true
      }
      else -> false
    }
    "printer" -> when {
      v is GridLayout && arg is Printer -> {
        v.setPrinter(arg)
        true
      }
      else -> false
    }
    "rowCount" -> when {
      v is GridLayout && arg is Int -> {
        v.setRowCount(arg)
        true
      }
      else -> false
    }
    "rowOrderPreserved" -> when {
      v is GridLayout && arg is Boolean -> {
        v.setRowOrderPreserved(arg)
        true
      }
      else -> false
    }
    "useDefaultMargins" -> when {
      v is GridLayout && arg is Boolean -> {
        v.setUseDefaultMargins(arg)
        true
      }
      else -> false
    }
    else -> false
  }
}
