@file:Suppress("DEPRECATION", "UNCHECKED_CAST", "MemberVisibilityCanBePrivate", "unused")

package dev.inkremental.dsl.androidx.recyclerview

import android.view.View
import androidx.recyclerview.widget.RecyclerView
import androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate
import dev.inkremental.Anvil
import kotlin.Any
import kotlin.Boolean
import kotlin.Function
import kotlin.Int
import kotlin.String
import kotlin.Suppress

/**
 * DSL for creating views and settings their attributes.
 * This file has been generated by
 * {@code gradle RecyclerViewv7Setter}
 * It contains views and their setters for the library recyclerview-v7.
 * Please, don't edit it manually unless for debugging.
 */
object RecyclerViewv7Setter : Anvil.AttributeSetter<Any> {
  override fun set(
    v: View,
    name: String,
    arg: Any?,
    old: Any?
  ): Boolean = when (name) {
    "accessibilityDelegateCompat" -> when {
      v is RecyclerView && arg is RecyclerViewAccessibilityDelegate? -> {
        v.setAccessibilityDelegateCompat(arg as RecyclerViewAccessibilityDelegate)
        true
      }
      else -> false
    }
    "adapter" -> when {
      v is RecyclerView && arg is RecyclerView.Adapter<*>? -> {
        v.setAdapter(arg as RecyclerView.Adapter<RecyclerView.ViewHolder>)
        true
      }
      else -> false
    }
    "childDrawingOrderCallback" -> when {
      v is RecyclerView && arg is RecyclerView.ChildDrawingOrderCallback? -> {
        v.setChildDrawingOrderCallback(arg as RecyclerView.ChildDrawingOrderCallback)
        true
      }
      else -> false
    }
    "edgeEffectFactory" -> when {
      v is RecyclerView && arg is RecyclerView.EdgeEffectFactory -> {
        v.setEdgeEffectFactory(arg)
        true
      }
      else -> false
    }
    "hasFixedSize" -> when {
      v is RecyclerView && arg is Boolean -> {
        v.setHasFixedSize(arg)
        true
      }
      else -> false
    }
    "itemAnimator" -> when {
      v is RecyclerView && arg is RecyclerView.ItemAnimator? -> {
        v.setItemAnimator(arg as RecyclerView.ItemAnimator)
        true
      }
      else -> false
    }
    "itemViewCacheSize" -> when {
      v is RecyclerView && arg is Int -> {
        v.setItemViewCacheSize(arg)
        true
      }
      else -> false
    }
    "layoutManager" -> when {
      v is RecyclerView && arg is RecyclerView.LayoutManager? -> {
        v.setLayoutManager(arg as RecyclerView.LayoutManager)
        true
      }
      else -> false
    }
    "onFling" -> when {
      v is RecyclerView -> when {
        arg == null -> {
          v.setOnFlingListener(null as? RecyclerView.OnFlingListener?)
          true
        }
        arg is Function<*> -> {
          arg as ((arg0: Int, arg1: Int) -> Boolean)?
          v.setOnFlingListener(object : RecyclerView.OnFlingListener() {
            override fun onFling(arg0: Int, arg1: Int): Boolean = arg(arg0, arg1).also {
                Anvil.render() }
          })
          true
        }
        else -> false
      }
      else -> false
    }
    "preserveFocusAfterLayout" -> when {
      v is RecyclerView && arg is Boolean -> {
        v.setPreserveFocusAfterLayout(arg)
        true
      }
      else -> false
    }
    "recycledViewPool" -> when {
      v is RecyclerView && arg is RecyclerView.RecycledViewPool? -> {
        v.setRecycledViewPool(arg as RecyclerView.RecycledViewPool)
        true
      }
      else -> false
    }
    "recyclerListener" -> when {
      v is RecyclerView && arg is RecyclerView.RecyclerListener? -> {
        v.setRecyclerListener(arg as RecyclerView.RecyclerListener)
        true
      }
      else -> false
    }
    "scrollingTouchSlop" -> when {
      v is RecyclerView && arg is Int -> {
        v.setScrollingTouchSlop(arg)
        true
      }
      else -> false
    }
    "viewCacheExtension" -> when {
      v is RecyclerView && arg is RecyclerView.ViewCacheExtension? -> {
        v.setViewCacheExtension(arg as RecyclerView.ViewCacheExtension)
        true
      }
      else -> false
    }
    else -> false
  }
}
