package trikita.anvil;

import android.app.SearchableInfo;
import android.content.res.ColorStateList;
import android.graphics.PorterDuff;
import android.graphics.Rect;
import android.graphics.Typeface;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.support.v4.view.ActionProvider;
import android.support.v4.widget.CursorAdapter;
import android.support.v7.view.menu.ActionMenuItemView;
import android.support.v7.view.menu.ExpandedMenuView;
import android.support.v7.view.menu.ListMenuItemView;
import android.support.v7.view.menu.MenuBuilder;
import android.support.v7.widget.ActionBarContainer;
import android.support.v7.widget.ActionBarContextView;
import android.support.v7.widget.ActionBarOverlayLayout;
import android.support.v7.widget.ActionMenuView;
import android.support.v7.widget.ActivityChooserView;
import android.support.v7.widget.AppCompatAutoCompleteTextView;
import android.support.v7.widget.AppCompatButton;
import android.support.v7.widget.AppCompatCheckBox;
import android.support.v7.widget.AppCompatCheckedTextView;
import android.support.v7.widget.AppCompatEditText;
import android.support.v7.widget.AppCompatImageButton;
import android.support.v7.widget.AppCompatImageView;
import android.support.v7.widget.AppCompatMultiAutoCompleteTextView;
import android.support.v7.widget.AppCompatRadioButton;
import android.support.v7.widget.AppCompatRatingBar;
import android.support.v7.widget.AppCompatSeekBar;
import android.support.v7.widget.AppCompatSpinner;
import android.support.v7.widget.AppCompatTextView;
import android.support.v7.widget.ButtonBarLayout;
import android.support.v7.widget.ContentFrameLayout;
import android.support.v7.widget.DialogTitle;
import android.support.v7.widget.FitWindowsFrameLayout;
import android.support.v7.widget.FitWindowsLinearLayout;
import android.support.v7.widget.FitWindowsViewGroup;
import android.support.v7.widget.LinearLayoutCompat;
import android.support.v7.widget.ListViewCompat;
import android.support.v7.widget.ScrollingTabContainerView;
import android.support.v7.widget.SearchView;
import android.support.v7.widget.SwitchCompat;
import android.support.v7.widget.Toolbar;
import android.support.v7.widget.ViewStubCompat;
import android.view.LayoutInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.Window;
import android.widget.PopupWindow;
import android.widget.SpinnerAdapter;
import java.lang.Boolean;
import java.lang.CharSequence;
import java.lang.Float;
import java.lang.Integer;
import java.lang.String;
import java.lang.Void;

/**
 * DSL for creating views and settings their attributes.
 * This file has been generated by {@code gradle generateAppCompatv7DSL}.
 * It contains views and their setters from the library appcompat-v7.
 * Please, don't edit it manually unless for debugging.
 */
public final class AppCompatv7DSL extends BaseDSL {
  public static AppCompatv7DSL.ViewClassResult actionMenuItemView() {
    return v(ActionMenuItemView.class);
  }

  public static Void actionMenuItemView(Anvil.Renderable r) {
    return v(ActionMenuItemView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult expandedMenuView() {
    return v(ExpandedMenuView.class);
  }

  public static Void expandedMenuView(Anvil.Renderable r) {
    return v(ExpandedMenuView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult listMenuItemView() {
    return v(ListMenuItemView.class);
  }

  public static Void listMenuItemView(Anvil.Renderable r) {
    return v(ListMenuItemView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult actionBarContainer() {
    return v(ActionBarContainer.class);
  }

  public static Void actionBarContainer(Anvil.Renderable r) {
    return v(ActionBarContainer.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult actionBarContextView() {
    return v(ActionBarContextView.class);
  }

  public static Void actionBarContextView(Anvil.Renderable r) {
    return v(ActionBarContextView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult actionBarOverlayLayout() {
    return v(ActionBarOverlayLayout.class);
  }

  public static Void actionBarOverlayLayout(Anvil.Renderable r) {
    return v(ActionBarOverlayLayout.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult actionMenuView() {
    return v(ActionMenuView.class);
  }

  public static Void actionMenuView(Anvil.Renderable r) {
    return v(ActionMenuView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult activityChooserView() {
    return v(ActivityChooserView.class);
  }

  public static Void activityChooserView(Anvil.Renderable r) {
    return v(ActivityChooserView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatAutoCompleteTextView() {
    return v(AppCompatAutoCompleteTextView.class);
  }

  public static Void appCompatAutoCompleteTextView(Anvil.Renderable r) {
    return v(AppCompatAutoCompleteTextView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatButton() {
    return v(AppCompatButton.class);
  }

  public static Void appCompatButton(Anvil.Renderable r) {
    return v(AppCompatButton.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatCheckBox() {
    return v(AppCompatCheckBox.class);
  }

  public static Void appCompatCheckBox(Anvil.Renderable r) {
    return v(AppCompatCheckBox.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatCheckedTextView() {
    return v(AppCompatCheckedTextView.class);
  }

  public static Void appCompatCheckedTextView(Anvil.Renderable r) {
    return v(AppCompatCheckedTextView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatEditText() {
    return v(AppCompatEditText.class);
  }

  public static Void appCompatEditText(Anvil.Renderable r) {
    return v(AppCompatEditText.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatImageButton() {
    return v(AppCompatImageButton.class);
  }

  public static Void appCompatImageButton(Anvil.Renderable r) {
    return v(AppCompatImageButton.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatImageView() {
    return v(AppCompatImageView.class);
  }

  public static Void appCompatImageView(Anvil.Renderable r) {
    return v(AppCompatImageView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatMultiAutoCompleteTextView() {
    return v(AppCompatMultiAutoCompleteTextView.class);
  }

  public static Void appCompatMultiAutoCompleteTextView(Anvil.Renderable r) {
    return v(AppCompatMultiAutoCompleteTextView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatRadioButton() {
    return v(AppCompatRadioButton.class);
  }

  public static Void appCompatRadioButton(Anvil.Renderable r) {
    return v(AppCompatRadioButton.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatRatingBar() {
    return v(AppCompatRatingBar.class);
  }

  public static Void appCompatRatingBar(Anvil.Renderable r) {
    return v(AppCompatRatingBar.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatSeekBar() {
    return v(AppCompatSeekBar.class);
  }

  public static Void appCompatSeekBar(Anvil.Renderable r) {
    return v(AppCompatSeekBar.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatSpinner() {
    return v(AppCompatSpinner.class);
  }

  public static Void appCompatSpinner(Anvil.Renderable r) {
    return v(AppCompatSpinner.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatTextView() {
    return v(AppCompatTextView.class);
  }

  public static Void appCompatTextView(Anvil.Renderable r) {
    return v(AppCompatTextView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult buttonBarLayout() {
    return v(ButtonBarLayout.class);
  }

  public static Void buttonBarLayout(Anvil.Renderable r) {
    return v(ButtonBarLayout.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult contentFrameLayout() {
    return v(ContentFrameLayout.class);
  }

  public static Void contentFrameLayout(Anvil.Renderable r) {
    return v(ContentFrameLayout.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult dialogTitle() {
    return v(DialogTitle.class);
  }

  public static Void dialogTitle(Anvil.Renderable r) {
    return v(DialogTitle.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult fitWindowsFrameLayout() {
    return v(FitWindowsFrameLayout.class);
  }

  public static Void fitWindowsFrameLayout(Anvil.Renderable r) {
    return v(FitWindowsFrameLayout.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult fitWindowsLinearLayout() {
    return v(FitWindowsLinearLayout.class);
  }

  public static Void fitWindowsLinearLayout(Anvil.Renderable r) {
    return v(FitWindowsLinearLayout.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult linearLayoutCompat() {
    return v(LinearLayoutCompat.class);
  }

  public static Void linearLayoutCompat(Anvil.Renderable r) {
    return v(LinearLayoutCompat.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult listViewCompat() {
    return v(ListViewCompat.class);
  }

  public static Void listViewCompat(Anvil.Renderable r) {
    return v(ListViewCompat.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult scrollingTabContainerView() {
    return v(ScrollingTabContainerView.class);
  }

  public static Void scrollingTabContainerView(Anvil.Renderable r) {
    return v(ScrollingTabContainerView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult searchView() {
    return v(SearchView.class);
  }

  public static Void searchView(Anvil.Renderable r) {
    return v(SearchView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult switchCompat() {
    return v(SwitchCompat.class);
  }

  public static Void switchCompat(Anvil.Renderable r) {
    return v(SwitchCompat.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult toolbar() {
    return v(Toolbar.class);
  }

  public static Void toolbar(Anvil.Renderable r) {
    return v(Toolbar.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult viewStubCompat() {
    return v(ViewStubCompat.class);
  }

  public static Void viewStubCompat(Anvil.Renderable r) {
    return v(ViewStubCompat.class, r);
  }

  public static Void actionBarHideOffset(int arg) {
    return AppCompatv7DSL.attr(ActionBarHideOffsetFunc8567756a.instance, arg);
  }

  public static Void actionBarVisibilityCallback(ActionBarOverlayLayout.ActionBarVisibilityCallback arg) {
    return AppCompatv7DSL.attr(ActionBarVisibilityCallbackFunccbf3fd1e.instance, arg);
  }

  public static Void adapter(SpinnerAdapter arg) {
    return AppCompatv7DSL.attr(AdapterFunc32a095c1.instance, arg);
  }

  public static Void allowCollapse(boolean arg) {
    return AppCompatv7DSL.attr(AllowCollapseFunc148d6054.instance, arg);
  }

  public static Void allowStacking(boolean arg) {
    return AppCompatv7DSL.attr(AllowStackingFunc148d6054.instance, arg);
  }

  public static Void appSearchData(Bundle arg) {
    return AppCompatv7DSL.attr(AppSearchDataFuncb92e972d.instance, arg);
  }

  public static Void attachListener(ContentFrameLayout.OnAttachListener arg) {
    return AppCompatv7DSL.attr(AttachListenerFunc3ca76dcd.instance, arg);
  }

  public static Void backgroundDrawable(Drawable arg) {
    return AppCompatv7DSL.attr(BackgroundDrawableFuncfb47464a.instance, arg);
  }

  public static Void backgroundResource(int arg) {
    return AppCompatv7DSL.attr(BackgroundResourceFunc8567756a.instance, arg);
  }

  public static Void baselineAligned(boolean arg) {
    return AppCompatv7DSL.attr(BaselineAlignedFunc148d6054.instance, arg);
  }

  public static Void baselineAlignedChildIndex(int arg) {
    return AppCompatv7DSL.attr(BaselineAlignedChildIndexFunc8567756a.instance, arg);
  }

  public static Void buttonDrawable(Drawable arg) {
    return AppCompatv7DSL.attr(ButtonDrawableFuncfb47464a.instance, arg);
  }

  public static Void buttonDrawable(int arg) {
    return AppCompatv7DSL.attr(ButtonDrawableFunc8567756a.instance, arg);
  }

  public static Void checkMarkDrawable(int arg) {
    return AppCompatv7DSL.attr(CheckMarkDrawableFunc8567756a.instance, arg);
  }

  public static Void checkable(boolean arg) {
    return AppCompatv7DSL.attr(CheckableFunc148d6054.instance, arg);
  }

  public static Void checked(boolean arg) {
    return AppCompatv7DSL.attr(CheckedFunc148d6054.instance, arg);
  }

  public static Void collapsible(boolean arg) {
    return AppCompatv7DSL.attr(CollapsibleFunc148d6054.instance, arg);
  }

  public static Void contentHeight(int arg) {
    return AppCompatv7DSL.attr(ContentHeightFunc8567756a.instance, arg);
  }

  public static Void customView(View arg) {
    return AppCompatv7DSL.attr(CustomViewFunc6c3617af.instance, arg);
  }

  public static Void defaultActionButtonContentDescription(int arg) {
    return AppCompatv7DSL.attr(DefaultActionButtonContentDescriptionFunc8567756a.instance, arg);
  }

  public static Void dividerDrawable(Drawable arg) {
    return AppCompatv7DSL.attr(DividerDrawableFuncfb47464a.instance, arg);
  }

  public static Void dividerPadding(int arg) {
    return AppCompatv7DSL.attr(DividerPaddingFunc8567756a.instance, arg);
  }

  public static Void dropDownBackgroundResource(int arg) {
    return AppCompatv7DSL.attr(DropDownBackgroundResourceFunc8567756a.instance, arg);
  }

  public static Void dropDownHorizontalOffset(int arg) {
    return AppCompatv7DSL.attr(DropDownHorizontalOffsetFunc8567756a.instance, arg);
  }

  public static Void dropDownVerticalOffset(int arg) {
    return AppCompatv7DSL.attr(DropDownVerticalOffsetFunc8567756a.instance, arg);
  }

  public static Void dropDownWidth(int arg) {
    return AppCompatv7DSL.attr(DropDownWidthFunc8567756a.instance, arg);
  }

  public static Void expandActivityOverflowButtonContentDescription(int arg) {
    return AppCompatv7DSL.attr(ExpandActivityOverflowButtonContentDescriptionFunc8567756a.instance, arg);
  }

  public static Void expandActivityOverflowButtonDrawable(Drawable arg) {
    return AppCompatv7DSL.attr(ExpandActivityOverflowButtonDrawableFuncfb47464a.instance, arg);
  }

  public static Void expandedActionViewsExclusive(boolean arg) {
    return AppCompatv7DSL.attr(ExpandedActionViewsExclusiveFunc148d6054.instance, arg);
  }

  public static Void expandedFormat(boolean arg) {
    return AppCompatv7DSL.attr(ExpandedFormatFunc148d6054.instance, arg);
  }

  public static Void forceShowIcon(boolean arg) {
    return AppCompatv7DSL.attr(ForceShowIconFunc148d6054.instance, arg);
  }

  public static Void gravity(int arg) {
    return AppCompatv7DSL.attr(GravityFunc8567756a.instance, arg);
  }

  public static Void hasNonEmbeddedTabs(boolean arg) {
    return AppCompatv7DSL.attr(HasNonEmbeddedTabsFunc148d6054.instance, arg);
  }

  public static Void hideOnContentScrollEnabled(boolean arg) {
    return AppCompatv7DSL.attr(HideOnContentScrollEnabledFunc148d6054.instance, arg);
  }

  public static Void horizontalGravity(int arg) {
    return AppCompatv7DSL.attr(HorizontalGravityFunc8567756a.instance, arg);
  }

  public static Void icon(Drawable arg) {
    return AppCompatv7DSL.attr(IconFuncfb47464a.instance, arg);
  }

  public static Void icon(int arg) {
    return AppCompatv7DSL.attr(IconFunc8567756a.instance, arg);
  }

  public static Void iconified(boolean arg) {
    return AppCompatv7DSL.attr(IconifiedFunc148d6054.instance, arg);
  }

  public static Void iconifiedByDefault(boolean arg) {
    return AppCompatv7DSL.attr(IconifiedByDefaultFunc148d6054.instance, arg);
  }

  public static Void imageResource(int arg) {
    return AppCompatv7DSL.attr(ImageResourceFunc8567756a.instance, arg);
  }

  public static Void imeOptions(int arg) {
    return AppCompatv7DSL.attr(ImeOptionsFunc8567756a.instance, arg);
  }

  public static Void inflatedId(int arg) {
    return AppCompatv7DSL.attr(InflatedIdFunc8567756a.instance, arg);
  }

  public static Void initialActivityCount(int arg) {
    return AppCompatv7DSL.attr(InitialActivityCountFunc8567756a.instance, arg);
  }

  public static Void inputType(int arg) {
    return AppCompatv7DSL.attr(InputTypeFunc8567756a.instance, arg);
  }

  public static Void itemInvoker(MenuBuilder.ItemInvoker arg) {
    return AppCompatv7DSL.attr(ItemInvokerFunc874ef140.instance, arg);
  }

  public static Void layoutInflater(LayoutInflater arg) {
    return AppCompatv7DSL.attr(LayoutInflaterFunc3f91d1f.instance, arg);
  }

  public static Void layoutResource(int arg) {
    return AppCompatv7DSL.attr(LayoutResourceFunc8567756a.instance, arg);
  }

  public static Void logo(Drawable arg) {
    return AppCompatv7DSL.attr(LogoFuncfb47464a.instance, arg);
  }

  public static Void logo(int arg) {
    return AppCompatv7DSL.attr(LogoFunc8567756a.instance, arg);
  }

  public static Void logoDescription(int arg) {
    return AppCompatv7DSL.attr(LogoDescriptionFunc8567756a.instance, arg);
  }

  public static Void logoDescription(CharSequence arg) {
    return AppCompatv7DSL.attr(LogoDescriptionFuncc0af808b.instance, arg);
  }

  public static Void maxWidth(int arg) {
    return AppCompatv7DSL.attr(MaxWidthFunc8567756a.instance, arg);
  }

  public static Void measureWithLargestChildEnabled(boolean arg) {
    return AppCompatv7DSL.attr(MeasureWithLargestChildEnabledFunc148d6054.instance, arg);
  }

  public static Void navigationContentDescription(int arg) {
    return AppCompatv7DSL.attr(NavigationContentDescriptionFunc8567756a.instance, arg);
  }

  public static Void navigationContentDescription(CharSequence arg) {
    return AppCompatv7DSL.attr(NavigationContentDescriptionFuncc0af808b.instance, arg);
  }

  public static Void navigationIcon(Drawable arg) {
    return AppCompatv7DSL.attr(NavigationIconFuncfb47464a.instance, arg);
  }

  public static Void navigationIcon(int arg) {
    return AppCompatv7DSL.attr(NavigationIconFunc8567756a.instance, arg);
  }

  public static Void navigationOnClickListener(View.OnClickListener arg) {
    return AppCompatv7DSL.attr(NavigationOnClickListenerFunc79a13a5e.instance, arg);
  }

  public static Void onClose(SearchView.OnCloseListener arg) {
    return AppCompatv7DSL.attr(OnCloseFuncfd9c6147.instance, arg);
  }

  public static Void onDismiss(PopupWindow.OnDismissListener arg) {
    return AppCompatv7DSL.attr(OnDismissFunc6b0eb982.instance, arg);
  }

  public static Void onFitSystemWindows(FitWindowsViewGroup.OnFitSystemWindowsListener arg) {
    return AppCompatv7DSL.attr(OnFitSystemWindowsFuncad8dd5d7.instance, arg);
  }

  public static Void onInflate(ViewStubCompat.OnInflateListener arg) {
    return AppCompatv7DSL.attr(OnInflateFuncb0ac3dfe.instance, arg);
  }

  public static Void onMenuItemClick(ActionMenuView.OnMenuItemClickListener arg) {
    return AppCompatv7DSL.attr(OnMenuItemClickFuncd1d929f2.instance, arg);
  }

  public static Void onMenuItemClick(Toolbar.OnMenuItemClickListener arg) {
    return AppCompatv7DSL.attr(OnMenuItemClickFunc68ab335d.instance, arg);
  }

  public static Void onQueryText(SearchView.OnQueryTextListener arg) {
    return AppCompatv7DSL.attr(OnQueryTextFunc59c08ee4.instance, arg);
  }

  public static Void onQueryTextFocusChange(View.OnFocusChangeListener arg) {
    return AppCompatv7DSL.attr(OnQueryTextFocusChangeFunca56a1dfe.instance, arg);
  }

  public static Void onSearchClick(View.OnClickListener arg) {
    return AppCompatv7DSL.attr(OnSearchClickFunc79a13a5e.instance, arg);
  }

  public static Void onSuggestion(SearchView.OnSuggestionListener arg) {
    return AppCompatv7DSL.attr(OnSuggestionFunc59f9313d.instance, arg);
  }

  public static Void orientation(int arg) {
    return AppCompatv7DSL.attr(OrientationFunc8567756a.instance, arg);
  }

  public static Void overflowIcon(Drawable arg) {
    return AppCompatv7DSL.attr(OverflowIconFuncfb47464a.instance, arg);
  }

  public static Void overflowReserved(boolean arg) {
    return AppCompatv7DSL.attr(OverflowReservedFunc148d6054.instance, arg);
  }

  public static Void overlayMode(boolean arg) {
    return AppCompatv7DSL.attr(OverlayModeFunc148d6054.instance, arg);
  }

  public static Void popupBackgroundDrawable(Drawable arg) {
    return AppCompatv7DSL.attr(PopupBackgroundDrawableFuncfb47464a.instance, arg);
  }

  public static Void popupBackgroundResource(int arg) {
    return AppCompatv7DSL.attr(PopupBackgroundResourceFunc8567756a.instance, arg);
  }

  public static Void popupCallback(ActionMenuItemView.PopupCallback arg) {
    return AppCompatv7DSL.attr(PopupCallbackFunc76c77ea5.instance, arg);
  }

  public static Void popupTheme(int arg) {
    return AppCompatv7DSL.attr(PopupThemeFunc8567756a.instance, arg);
  }

  public static Void primaryBackground(Drawable arg) {
    return AppCompatv7DSL.attr(PrimaryBackgroundFuncfb47464a.instance, arg);
  }

  public static Void prompt(CharSequence arg) {
    return AppCompatv7DSL.attr(PromptFuncc0af808b.instance, arg);
  }

  public static Void provider(ActionProvider arg) {
    return AppCompatv7DSL.attr(ProviderFunc66da8dbe.instance, arg);
  }

  public static Void queryHint(CharSequence arg) {
    return AppCompatv7DSL.attr(QueryHintFuncc0af808b.instance, arg);
  }

  public static Void queryRefinementEnabled(boolean arg) {
    return AppCompatv7DSL.attr(QueryRefinementEnabledFunc148d6054.instance, arg);
  }

  public static Void searchableInfo(SearchableInfo arg) {
    return AppCompatv7DSL.attr(SearchableInfoFunc1f96c03c.instance, arg);
  }

  public static Void selector(Drawable arg) {
    return AppCompatv7DSL.attr(SelectorFuncfb47464a.instance, arg);
  }

  public static Void showDividers(int arg) {
    return AppCompatv7DSL.attr(ShowDividersFunc8567756a.instance, arg);
  }

  public static Void showText(boolean arg) {
    return AppCompatv7DSL.attr(ShowTextFunc148d6054.instance, arg);
  }

  public static Void showingForActionMode(boolean arg) {
    return AppCompatv7DSL.attr(ShowingForActionModeFunc148d6054.instance, arg);
  }

  public static Void splitBackground(Drawable arg) {
    return AppCompatv7DSL.attr(SplitBackgroundFuncfb47464a.instance, arg);
  }

  public static Void splitTrack(boolean arg) {
    return AppCompatv7DSL.attr(SplitTrackFunc148d6054.instance, arg);
  }

  public static Void stackedBackground(Drawable arg) {
    return AppCompatv7DSL.attr(StackedBackgroundFuncfb47464a.instance, arg);
  }

  public static Void submitButtonEnabled(boolean arg) {
    return AppCompatv7DSL.attr(SubmitButtonEnabledFunc148d6054.instance, arg);
  }

  public static Void subtitle(int arg) {
    return AppCompatv7DSL.attr(SubtitleFunc8567756a.instance, arg);
  }

  public static Void subtitle(CharSequence arg) {
    return AppCompatv7DSL.attr(SubtitleFuncc0af808b.instance, arg);
  }

  public static Void subtitleTextColor(int arg) {
    return AppCompatv7DSL.attr(SubtitleTextColorFunc8567756a.instance, arg);
  }

  public static Void suggestionsAdapter(CursorAdapter arg) {
    return AppCompatv7DSL.attr(SuggestionsAdapterFuncb430a5a1.instance, arg);
  }

  public static Void supportAllCaps(boolean arg) {
    return AppCompatv7DSL.attr(SupportAllCapsFunc148d6054.instance, arg);
  }

  public static Void supportBackgroundTintList(ColorStateList arg) {
    return AppCompatv7DSL.attr(SupportBackgroundTintListFunc9e5e0e4e.instance, arg);
  }

  public static Void supportBackgroundTintMode(PorterDuff.Mode arg) {
    return AppCompatv7DSL.attr(SupportBackgroundTintModeFuncabb7a84e.instance, arg);
  }

  public static Void supportButtonTintList(ColorStateList arg) {
    return AppCompatv7DSL.attr(SupportButtonTintListFunc9e5e0e4e.instance, arg);
  }

  public static Void supportButtonTintMode(PorterDuff.Mode arg) {
    return AppCompatv7DSL.attr(SupportButtonTintModeFuncabb7a84e.instance, arg);
  }

  public static Void switchMinWidth(int arg) {
    return AppCompatv7DSL.attr(SwitchMinWidthFunc8567756a.instance, arg);
  }

  public static Void switchPadding(int arg) {
    return AppCompatv7DSL.attr(SwitchPaddingFunc8567756a.instance, arg);
  }

  public static Void switchTypeface(Typeface arg) {
    return AppCompatv7DSL.attr(SwitchTypefaceFunc53b4afb.instance, arg);
  }

  public static Void tabContainer(ScrollingTabContainerView arg) {
    return AppCompatv7DSL.attr(TabContainerFunc1a5e642b.instance, arg);
  }

  public static Void tabSelected(int arg) {
    return AppCompatv7DSL.attr(TabSelectedFunc8567756a.instance, arg);
  }

  public static Void textOff(CharSequence arg) {
    return AppCompatv7DSL.attr(TextOffFuncc0af808b.instance, arg);
  }

  public static Void textOn(CharSequence arg) {
    return AppCompatv7DSL.attr(TextOnFuncc0af808b.instance, arg);
  }

  public static Void thumbDrawable(Drawable arg) {
    return AppCompatv7DSL.attr(ThumbDrawableFuncfb47464a.instance, arg);
  }

  public static Void thumbResource(int arg) {
    return AppCompatv7DSL.attr(ThumbResourceFunc8567756a.instance, arg);
  }

  public static Void thumbTextPadding(int arg) {
    return AppCompatv7DSL.attr(ThumbTextPaddingFunc8567756a.instance, arg);
  }

  public static Void title(int arg) {
    return AppCompatv7DSL.attr(TitleFunc8567756a.instance, arg);
  }

  public static Void title(CharSequence arg) {
    return AppCompatv7DSL.attr(TitleFuncc0af808b.instance, arg);
  }

  public static Void titleOptional(boolean arg) {
    return AppCompatv7DSL.attr(TitleOptionalFunc148d6054.instance, arg);
  }

  public static Void titleTextColor(int arg) {
    return AppCompatv7DSL.attr(TitleTextColorFunc8567756a.instance, arg);
  }

  public static Void trackDrawable(Drawable arg) {
    return AppCompatv7DSL.attr(TrackDrawableFuncfb47464a.instance, arg);
  }

  public static Void trackResource(int arg) {
    return AppCompatv7DSL.attr(TrackResourceFunc8567756a.instance, arg);
  }

  public static Void transitioning(boolean arg) {
    return AppCompatv7DSL.attr(TransitioningFunc148d6054.instance, arg);
  }

  public static Void uiOptions(int arg) {
    return AppCompatv7DSL.attr(UiOptionsFunc8567756a.instance, arg);
  }

  public static Void verticalGravity(int arg) {
    return AppCompatv7DSL.attr(VerticalGravityFunc8567756a.instance, arg);
  }

  public static Void visibility(int arg) {
    return AppCompatv7DSL.attr(VisibilityFunc8567756a.instance, arg);
  }

  public static Void weightSum(float arg) {
    return AppCompatv7DSL.attr(WeightSumFunce0893188.instance, arg);
  }

  public static Void windowCallback(Window.Callback arg) {
    return AppCompatv7DSL.attr(WindowCallbackFunc13cc8159.instance, arg);
  }

  public static Void windowTitle(CharSequence arg) {
    return AppCompatv7DSL.attr(WindowTitleFuncc0af808b.instance, arg);
  }

  private static final class ActionBarHideOffsetFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ActionBarHideOffsetFunc8567756a instance = new ActionBarHideOffsetFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setActionBarHideOffset(arg);
      }
    }
  }

  private static final class ActionBarVisibilityCallbackFunccbf3fd1e implements Anvil.AttrFunc<ActionBarOverlayLayout.ActionBarVisibilityCallback> {
    public static final ActionBarVisibilityCallbackFunccbf3fd1e instance = new ActionBarVisibilityCallbackFunccbf3fd1e();

    public void apply(View v, final ActionBarOverlayLayout.ActionBarVisibilityCallback arg, final ActionBarOverlayLayout.ActionBarVisibilityCallback old) {
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setActionBarVisibilityCallback(arg);
      }
    }
  }

  private static final class AdapterFunc32a095c1 implements Anvil.AttrFunc<SpinnerAdapter> {
    public static final AdapterFunc32a095c1 instance = new AdapterFunc32a095c1();

    public void apply(View v, final SpinnerAdapter arg, final SpinnerAdapter old) {
      if (v instanceof AppCompatSpinner) {
        ((AppCompatSpinner) v).setAdapter(arg);
      }
    }
  }

  private static final class AllowCollapseFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final AllowCollapseFunc148d6054 instance = new AllowCollapseFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ScrollingTabContainerView) {
        ((ScrollingTabContainerView) v).setAllowCollapse(arg);
      }
    }
  }

  private static final class AllowStackingFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final AllowStackingFunc148d6054 instance = new AllowStackingFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ButtonBarLayout) {
        ((ButtonBarLayout) v).setAllowStacking(arg);
      }
    }
  }

  private static final class AppSearchDataFuncb92e972d implements Anvil.AttrFunc<Bundle> {
    public static final AppSearchDataFuncb92e972d instance = new AppSearchDataFuncb92e972d();

    public void apply(View v, final Bundle arg, final Bundle old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setAppSearchData(arg);
      }
    }
  }

  private static final class AttachListenerFunc3ca76dcd implements Anvil.AttrFunc<ContentFrameLayout.OnAttachListener> {
    public static final AttachListenerFunc3ca76dcd instance = new AttachListenerFunc3ca76dcd();

    public void apply(View v, final ContentFrameLayout.OnAttachListener arg, final ContentFrameLayout.OnAttachListener old) {
      if (v instanceof ContentFrameLayout) {
        ((ContentFrameLayout) v).setAttachListener(arg);
      }
    }
  }

  private static final class BackgroundDrawableFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final BackgroundDrawableFuncfb47464a instance = new BackgroundDrawableFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof AppCompatAutoCompleteTextView) {
        ((AppCompatAutoCompleteTextView) v).setBackgroundDrawable(arg);
      }
      if (v instanceof AppCompatButton) {
        ((AppCompatButton) v).setBackgroundDrawable(arg);
      }
      if (v instanceof AppCompatEditText) {
        ((AppCompatEditText) v).setBackgroundDrawable(arg);
      }
      if (v instanceof AppCompatImageButton) {
        ((AppCompatImageButton) v).setBackgroundDrawable(arg);
      }
      if (v instanceof AppCompatImageView) {
        ((AppCompatImageView) v).setBackgroundDrawable(arg);
      }
      if (v instanceof AppCompatMultiAutoCompleteTextView) {
        ((AppCompatMultiAutoCompleteTextView) v).setBackgroundDrawable(arg);
      }
      if (v instanceof AppCompatSpinner) {
        ((AppCompatSpinner) v).setBackgroundDrawable(arg);
      }
      if (v instanceof AppCompatTextView) {
        ((AppCompatTextView) v).setBackgroundDrawable(arg);
      }
    }
  }

  private static final class BackgroundResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final BackgroundResourceFunc8567756a instance = new BackgroundResourceFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof AppCompatAutoCompleteTextView) {
        ((AppCompatAutoCompleteTextView) v).setBackgroundResource(arg);
      }
      if (v instanceof AppCompatButton) {
        ((AppCompatButton) v).setBackgroundResource(arg);
      }
      if (v instanceof AppCompatEditText) {
        ((AppCompatEditText) v).setBackgroundResource(arg);
      }
      if (v instanceof AppCompatImageButton) {
        ((AppCompatImageButton) v).setBackgroundResource(arg);
      }
      if (v instanceof AppCompatImageView) {
        ((AppCompatImageView) v).setBackgroundResource(arg);
      }
      if (v instanceof AppCompatMultiAutoCompleteTextView) {
        ((AppCompatMultiAutoCompleteTextView) v).setBackgroundResource(arg);
      }
      if (v instanceof AppCompatSpinner) {
        ((AppCompatSpinner) v).setBackgroundResource(arg);
      }
      if (v instanceof AppCompatTextView) {
        ((AppCompatTextView) v).setBackgroundResource(arg);
      }
    }
  }

  private static final class BaselineAlignedFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final BaselineAlignedFunc148d6054 instance = new BaselineAlignedFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setBaselineAligned(arg);
      }
    }
  }

  private static final class BaselineAlignedChildIndexFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final BaselineAlignedChildIndexFunc8567756a instance = new BaselineAlignedChildIndexFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setBaselineAlignedChildIndex(arg);
      }
    }
  }

  private static final class ButtonDrawableFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final ButtonDrawableFuncfb47464a instance = new ButtonDrawableFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof AppCompatCheckBox) {
        ((AppCompatCheckBox) v).setButtonDrawable(arg);
      }
      if (v instanceof AppCompatRadioButton) {
        ((AppCompatRadioButton) v).setButtonDrawable(arg);
      }
    }
  }

  private static final class ButtonDrawableFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ButtonDrawableFunc8567756a instance = new ButtonDrawableFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof AppCompatCheckBox) {
        ((AppCompatCheckBox) v).setButtonDrawable(arg);
      }
      if (v instanceof AppCompatRadioButton) {
        ((AppCompatRadioButton) v).setButtonDrawable(arg);
      }
    }
  }

  private static final class CheckMarkDrawableFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final CheckMarkDrawableFunc8567756a instance = new CheckMarkDrawableFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof AppCompatCheckedTextView) {
        ((AppCompatCheckedTextView) v).setCheckMarkDrawable(arg);
      }
    }
  }

  private static final class CheckableFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final CheckableFunc148d6054 instance = new CheckableFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionMenuItemView) {
        ((ActionMenuItemView) v).setCheckable(arg);
      }
      if (v instanceof ListMenuItemView) {
        ((ListMenuItemView) v).setCheckable(arg);
      }
    }
  }

  private static final class CheckedFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final CheckedFunc148d6054 instance = new CheckedFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionMenuItemView) {
        ((ActionMenuItemView) v).setChecked(arg);
      }
      if (v instanceof ListMenuItemView) {
        ((ListMenuItemView) v).setChecked(arg);
      }
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setChecked(arg);
      }
    }
  }

  private static final class CollapsibleFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final CollapsibleFunc148d6054 instance = new CollapsibleFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setCollapsible(arg);
      }
    }
  }

  private static final class ContentHeightFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ContentHeightFunc8567756a instance = new ContentHeightFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActionBarContextView) {
        ((ActionBarContextView) v).setContentHeight(arg);
      }
      if (v instanceof ScrollingTabContainerView) {
        ((ScrollingTabContainerView) v).setContentHeight(arg);
      }
    }
  }

  private static final class CustomViewFunc6c3617af implements Anvil.AttrFunc<View> {
    public static final CustomViewFunc6c3617af instance = new CustomViewFunc6c3617af();

    public void apply(View v, final View arg, final View old) {
      if (v instanceof ActionBarContextView) {
        ((ActionBarContextView) v).setCustomView(arg);
      }
    }
  }

  private static final class DefaultActionButtonContentDescriptionFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final DefaultActionButtonContentDescriptionFunc8567756a instance = new DefaultActionButtonContentDescriptionFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setDefaultActionButtonContentDescription(arg);
      }
    }
  }

  private static final class DividerDrawableFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final DividerDrawableFuncfb47464a instance = new DividerDrawableFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setDividerDrawable(arg);
      }
    }
  }

  private static final class DividerPaddingFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final DividerPaddingFunc8567756a instance = new DividerPaddingFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setDividerPadding(arg);
      }
    }
  }

  private static final class DropDownBackgroundResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final DropDownBackgroundResourceFunc8567756a instance = new DropDownBackgroundResourceFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof AppCompatAutoCompleteTextView) {
        ((AppCompatAutoCompleteTextView) v).setDropDownBackgroundResource(arg);
      }
      if (v instanceof AppCompatMultiAutoCompleteTextView) {
        ((AppCompatMultiAutoCompleteTextView) v).setDropDownBackgroundResource(arg);
      }
    }
  }

  private static final class DropDownHorizontalOffsetFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final DropDownHorizontalOffsetFunc8567756a instance = new DropDownHorizontalOffsetFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof AppCompatSpinner) {
        ((AppCompatSpinner) v).setDropDownHorizontalOffset(arg);
      }
    }
  }

  private static final class DropDownVerticalOffsetFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final DropDownVerticalOffsetFunc8567756a instance = new DropDownVerticalOffsetFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof AppCompatSpinner) {
        ((AppCompatSpinner) v).setDropDownVerticalOffset(arg);
      }
    }
  }

  private static final class DropDownWidthFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final DropDownWidthFunc8567756a instance = new DropDownWidthFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof AppCompatSpinner) {
        ((AppCompatSpinner) v).setDropDownWidth(arg);
      }
    }
  }

  private static final class ExpandActivityOverflowButtonContentDescriptionFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ExpandActivityOverflowButtonContentDescriptionFunc8567756a instance = new ExpandActivityOverflowButtonContentDescriptionFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setExpandActivityOverflowButtonContentDescription(arg);
      }
    }
  }

  private static final class ExpandActivityOverflowButtonDrawableFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final ExpandActivityOverflowButtonDrawableFuncfb47464a instance = new ExpandActivityOverflowButtonDrawableFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setExpandActivityOverflowButtonDrawable(arg);
      }
    }
  }

  private static final class ExpandedActionViewsExclusiveFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final ExpandedActionViewsExclusiveFunc148d6054 instance = new ExpandedActionViewsExclusiveFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionMenuView) {
        ((ActionMenuView) v).setExpandedActionViewsExclusive(arg);
      }
    }
  }

  private static final class ExpandedFormatFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final ExpandedFormatFunc148d6054 instance = new ExpandedFormatFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionMenuItemView) {
        ((ActionMenuItemView) v).setExpandedFormat(arg);
      }
    }
  }

  private static final class ForceShowIconFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final ForceShowIconFunc148d6054 instance = new ForceShowIconFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ListMenuItemView) {
        ((ListMenuItemView) v).setForceShowIcon(arg);
      }
    }
  }

  private static final class GravityFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final GravityFunc8567756a instance = new GravityFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setGravity(arg);
      }
    }
  }

  private static final class HasNonEmbeddedTabsFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final HasNonEmbeddedTabsFunc148d6054 instance = new HasNonEmbeddedTabsFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setHasNonEmbeddedTabs(arg);
      }
    }
  }

  private static final class HideOnContentScrollEnabledFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final HideOnContentScrollEnabledFunc148d6054 instance = new HideOnContentScrollEnabledFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setHideOnContentScrollEnabled(arg);
      }
    }
  }

  private static final class HorizontalGravityFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final HorizontalGravityFunc8567756a instance = new HorizontalGravityFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setHorizontalGravity(arg);
      }
    }
  }

  private static final class IconFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final IconFuncfb47464a instance = new IconFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ActionMenuItemView) {
        ((ActionMenuItemView) v).setIcon(arg);
      }
      if (v instanceof ListMenuItemView) {
        ((ListMenuItemView) v).setIcon(arg);
      }
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setIcon(arg);
      }
    }
  }

  private static final class IconFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final IconFunc8567756a instance = new IconFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setIcon(arg);
      }
    }
  }

  private static final class IconifiedFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final IconifiedFunc148d6054 instance = new IconifiedFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setIconified(arg);
      }
    }
  }

  private static final class IconifiedByDefaultFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final IconifiedByDefaultFunc148d6054 instance = new IconifiedByDefaultFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setIconifiedByDefault(arg);
      }
    }
  }

  private static final class ImageResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ImageResourceFunc8567756a instance = new ImageResourceFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof AppCompatImageButton) {
        ((AppCompatImageButton) v).setImageResource(arg);
      }
      if (v instanceof AppCompatImageView) {
        ((AppCompatImageView) v).setImageResource(arg);
      }
    }
  }

  private static final class ImeOptionsFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ImeOptionsFunc8567756a instance = new ImeOptionsFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setImeOptions(arg);
      }
    }
  }

  private static final class InflatedIdFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final InflatedIdFunc8567756a instance = new InflatedIdFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ViewStubCompat) {
        ((ViewStubCompat) v).setInflatedId(arg);
      }
    }
  }

  private static final class InitialActivityCountFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final InitialActivityCountFunc8567756a instance = new InitialActivityCountFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setInitialActivityCount(arg);
      }
    }
  }

  private static final class InputTypeFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final InputTypeFunc8567756a instance = new InputTypeFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setInputType(arg);
      }
    }
  }

  private static final class ItemInvokerFunc874ef140 implements Anvil.AttrFunc<MenuBuilder.ItemInvoker> {
    public static final ItemInvokerFunc874ef140 instance = new ItemInvokerFunc874ef140();

    public void apply(View v, final MenuBuilder.ItemInvoker arg, final MenuBuilder.ItemInvoker old) {
      if (v instanceof ActionMenuItemView) {
        ((ActionMenuItemView) v).setItemInvoker(arg);
      }
    }
  }

  private static final class LayoutInflaterFunc3f91d1f implements Anvil.AttrFunc<LayoutInflater> {
    public static final LayoutInflaterFunc3f91d1f instance = new LayoutInflaterFunc3f91d1f();

    public void apply(View v, final LayoutInflater arg, final LayoutInflater old) {
      if (v instanceof ViewStubCompat) {
        ((ViewStubCompat) v).setLayoutInflater(arg);
      }
    }
  }

  private static final class LayoutResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final LayoutResourceFunc8567756a instance = new LayoutResourceFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ViewStubCompat) {
        ((ViewStubCompat) v).setLayoutResource(arg);
      }
    }
  }

  private static final class LogoFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final LogoFuncfb47464a instance = new LogoFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setLogo(arg);
      }
    }
  }

  private static final class LogoFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final LogoFunc8567756a instance = new LogoFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setLogo(arg);
      }
      if (v instanceof Toolbar) {
        ((Toolbar) v).setLogo(arg);
      }
    }
  }

  private static final class LogoDescriptionFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final LogoDescriptionFunc8567756a instance = new LogoDescriptionFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setLogoDescription(arg);
      }
    }
  }

  private static final class LogoDescriptionFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final LogoDescriptionFuncc0af808b instance = new LogoDescriptionFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setLogoDescription(arg);
      }
    }
  }

  private static final class MaxWidthFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final MaxWidthFunc8567756a instance = new MaxWidthFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setMaxWidth(arg);
      }
    }
  }

  private static final class MeasureWithLargestChildEnabledFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final MeasureWithLargestChildEnabledFunc148d6054 instance = new MeasureWithLargestChildEnabledFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setMeasureWithLargestChildEnabled(arg);
      }
    }
  }

  private static final class NavigationContentDescriptionFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final NavigationContentDescriptionFunc8567756a instance = new NavigationContentDescriptionFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setNavigationContentDescription(arg);
      }
    }
  }

  private static final class NavigationContentDescriptionFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final NavigationContentDescriptionFuncc0af808b instance = new NavigationContentDescriptionFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setNavigationContentDescription(arg);
      }
    }
  }

  private static final class NavigationIconFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final NavigationIconFuncfb47464a instance = new NavigationIconFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setNavigationIcon(arg);
      }
    }
  }

  private static final class NavigationIconFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final NavigationIconFunc8567756a instance = new NavigationIconFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setNavigationIcon(arg);
      }
    }
  }

  private static final class NavigationOnClickListenerFunc79a13a5e implements Anvil.AttrFunc<View.OnClickListener> {
    public static final NavigationOnClickListenerFunc79a13a5e instance = new NavigationOnClickListenerFunc79a13a5e();

    public void apply(View v, final View.OnClickListener arg, final View.OnClickListener old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setNavigationOnClickListener(arg);
      }
    }
  }

  private static final class OnCloseFuncfd9c6147 implements Anvil.AttrFunc<SearchView.OnCloseListener> {
    public static final OnCloseFuncfd9c6147 instance = new OnCloseFuncfd9c6147();

    public void apply(View v, final SearchView.OnCloseListener arg, final SearchView.OnCloseListener old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setOnCloseListener(new SearchView.OnCloseListener() {
          public boolean onClose() {
            boolean r = arg.onClose();
            Anvil.render();
            return r;
          }
        });
      }
    }
  }

  private static final class OnDismissFunc6b0eb982 implements Anvil.AttrFunc<PopupWindow.OnDismissListener> {
    public static final OnDismissFunc6b0eb982 instance = new OnDismissFunc6b0eb982();

    public void apply(View v, final PopupWindow.OnDismissListener arg, final PopupWindow.OnDismissListener old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setOnDismissListener(new PopupWindow.OnDismissListener() {
          public void onDismiss() {
            arg.onDismiss();
            Anvil.render();
          }
        });
      }
    }
  }

  private static final class OnFitSystemWindowsFuncad8dd5d7 implements Anvil.AttrFunc<FitWindowsViewGroup.OnFitSystemWindowsListener> {
    public static final OnFitSystemWindowsFuncad8dd5d7 instance = new OnFitSystemWindowsFuncad8dd5d7();

    public void apply(View v, final FitWindowsViewGroup.OnFitSystemWindowsListener arg, final FitWindowsViewGroup.OnFitSystemWindowsListener old) {
      if (v instanceof FitWindowsFrameLayout) {
        ((FitWindowsFrameLayout) v).setOnFitSystemWindowsListener(new FitWindowsViewGroup.OnFitSystemWindowsListener() {
          public void onFitSystemWindows(Rect a0) {
            arg.onFitSystemWindows(a0);
            Anvil.render();
          }
        });
      }
      if (v instanceof FitWindowsLinearLayout) {
        ((FitWindowsLinearLayout) v).setOnFitSystemWindowsListener(new FitWindowsViewGroup.OnFitSystemWindowsListener() {
          public void onFitSystemWindows(Rect a0) {
            arg.onFitSystemWindows(a0);
            Anvil.render();
          }
        });
      }
    }
  }

  private static final class OnInflateFuncb0ac3dfe implements Anvil.AttrFunc<ViewStubCompat.OnInflateListener> {
    public static final OnInflateFuncb0ac3dfe instance = new OnInflateFuncb0ac3dfe();

    public void apply(View v, final ViewStubCompat.OnInflateListener arg, final ViewStubCompat.OnInflateListener old) {
      if (v instanceof ViewStubCompat) {
        ((ViewStubCompat) v).setOnInflateListener(new ViewStubCompat.OnInflateListener() {
          public void onInflate(ViewStubCompat a0, View a1) {
            arg.onInflate(a0, a1);
            Anvil.render();
          }
        });
      }
    }
  }

  private static final class OnMenuItemClickFuncd1d929f2 implements Anvil.AttrFunc<ActionMenuView.OnMenuItemClickListener> {
    public static final OnMenuItemClickFuncd1d929f2 instance = new OnMenuItemClickFuncd1d929f2();

    public void apply(View v, final ActionMenuView.OnMenuItemClickListener arg, final ActionMenuView.OnMenuItemClickListener old) {
      if (v instanceof ActionMenuView) {
        ((ActionMenuView) v).setOnMenuItemClickListener(new ActionMenuView.OnMenuItemClickListener() {
          public boolean onMenuItemClick(MenuItem a0) {
            boolean r = arg.onMenuItemClick(a0);
            Anvil.render();
            return r;
          }
        });
      }
    }
  }

  private static final class OnMenuItemClickFunc68ab335d implements Anvil.AttrFunc<Toolbar.OnMenuItemClickListener> {
    public static final OnMenuItemClickFunc68ab335d instance = new OnMenuItemClickFunc68ab335d();

    public void apply(View v, final Toolbar.OnMenuItemClickListener arg, final Toolbar.OnMenuItemClickListener old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setOnMenuItemClickListener(new Toolbar.OnMenuItemClickListener() {
          public boolean onMenuItemClick(MenuItem a0) {
            boolean r = arg.onMenuItemClick(a0);
            Anvil.render();
            return r;
          }
        });
      }
    }
  }

  private static final class OnQueryTextFunc59c08ee4 implements Anvil.AttrFunc<SearchView.OnQueryTextListener> {
    public static final OnQueryTextFunc59c08ee4 instance = new OnQueryTextFunc59c08ee4();

    public void apply(View v, final SearchView.OnQueryTextListener arg, final SearchView.OnQueryTextListener old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setOnQueryTextListener(new SearchView.OnQueryTextListener() {
          public boolean onQueryTextChange(String a0) {
            boolean r = arg.onQueryTextChange(a0);
            Anvil.render();
            return r;
          }

          public boolean onQueryTextSubmit(String a0) {
            boolean r = arg.onQueryTextSubmit(a0);
            Anvil.render();
            return r;
          }
        });
      }
    }
  }

  private static final class OnQueryTextFocusChangeFunca56a1dfe implements Anvil.AttrFunc<View.OnFocusChangeListener> {
    public static final OnQueryTextFocusChangeFunca56a1dfe instance = new OnQueryTextFocusChangeFunca56a1dfe();

    public void apply(View v, final View.OnFocusChangeListener arg, final View.OnFocusChangeListener old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setOnQueryTextFocusChangeListener(new View.OnFocusChangeListener() {
          public void onFocusChange(View a0, boolean a1) {
            arg.onFocusChange(a0, a1);
            Anvil.render();
          }
        });
      }
    }
  }

  private static final class OnSearchClickFunc79a13a5e implements Anvil.AttrFunc<View.OnClickListener> {
    public static final OnSearchClickFunc79a13a5e instance = new OnSearchClickFunc79a13a5e();

    public void apply(View v, final View.OnClickListener arg, final View.OnClickListener old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setOnSearchClickListener(new View.OnClickListener() {
          public void onClick(View a0) {
            arg.onClick(a0);
            Anvil.render();
          }
        });
      }
    }
  }

  private static final class OnSuggestionFunc59f9313d implements Anvil.AttrFunc<SearchView.OnSuggestionListener> {
    public static final OnSuggestionFunc59f9313d instance = new OnSuggestionFunc59f9313d();

    public void apply(View v, final SearchView.OnSuggestionListener arg, final SearchView.OnSuggestionListener old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setOnSuggestionListener(new SearchView.OnSuggestionListener() {
          public boolean onSuggestionClick(int a0) {
            boolean r = arg.onSuggestionClick(a0);
            Anvil.render();
            return r;
          }

          public boolean onSuggestionSelect(int a0) {
            boolean r = arg.onSuggestionSelect(a0);
            Anvil.render();
            return r;
          }
        });
      }
    }
  }

  private static final class OrientationFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final OrientationFunc8567756a instance = new OrientationFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setOrientation(arg);
      }
    }
  }

  private static final class OverflowIconFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final OverflowIconFuncfb47464a instance = new OverflowIconFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ActionMenuView) {
        ((ActionMenuView) v).setOverflowIcon(arg);
      }
      if (v instanceof Toolbar) {
        ((Toolbar) v).setOverflowIcon(arg);
      }
    }
  }

  private static final class OverflowReservedFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final OverflowReservedFunc148d6054 instance = new OverflowReservedFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionMenuView) {
        ((ActionMenuView) v).setOverflowReserved(arg);
      }
    }
  }

  private static final class OverlayModeFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final OverlayModeFunc148d6054 instance = new OverlayModeFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setOverlayMode(arg);
      }
    }
  }

  private static final class PopupBackgroundDrawableFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final PopupBackgroundDrawableFuncfb47464a instance = new PopupBackgroundDrawableFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof AppCompatSpinner) {
        ((AppCompatSpinner) v).setPopupBackgroundDrawable(arg);
      }
    }
  }

  private static final class PopupBackgroundResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final PopupBackgroundResourceFunc8567756a instance = new PopupBackgroundResourceFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof AppCompatSpinner) {
        ((AppCompatSpinner) v).setPopupBackgroundResource(arg);
      }
    }
  }

  private static final class PopupCallbackFunc76c77ea5 implements Anvil.AttrFunc<ActionMenuItemView.PopupCallback> {
    public static final PopupCallbackFunc76c77ea5 instance = new PopupCallbackFunc76c77ea5();

    public void apply(View v, final ActionMenuItemView.PopupCallback arg, final ActionMenuItemView.PopupCallback old) {
      if (v instanceof ActionMenuItemView) {
        ((ActionMenuItemView) v).setPopupCallback(arg);
      }
    }
  }

  private static final class PopupThemeFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final PopupThemeFunc8567756a instance = new PopupThemeFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActionMenuView) {
        ((ActionMenuView) v).setPopupTheme(arg);
      }
      if (v instanceof Toolbar) {
        ((Toolbar) v).setPopupTheme(arg);
      }
    }
  }

  private static final class PrimaryBackgroundFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final PrimaryBackgroundFuncfb47464a instance = new PrimaryBackgroundFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ActionBarContainer) {
        ((ActionBarContainer) v).setPrimaryBackground(arg);
      }
    }
  }

  private static final class PromptFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final PromptFuncc0af808b instance = new PromptFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof AppCompatSpinner) {
        ((AppCompatSpinner) v).setPrompt(arg);
      }
    }
  }

  private static final class ProviderFunc66da8dbe implements Anvil.AttrFunc<ActionProvider> {
    public static final ProviderFunc66da8dbe instance = new ProviderFunc66da8dbe();

    public void apply(View v, final ActionProvider arg, final ActionProvider old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setProvider(arg);
      }
    }
  }

  private static final class QueryHintFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final QueryHintFuncc0af808b instance = new QueryHintFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setQueryHint(arg);
      }
    }
  }

  private static final class QueryRefinementEnabledFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final QueryRefinementEnabledFunc148d6054 instance = new QueryRefinementEnabledFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setQueryRefinementEnabled(arg);
      }
    }
  }

  private static final class SearchableInfoFunc1f96c03c implements Anvil.AttrFunc<SearchableInfo> {
    public static final SearchableInfoFunc1f96c03c instance = new SearchableInfoFunc1f96c03c();

    public void apply(View v, final SearchableInfo arg, final SearchableInfo old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setSearchableInfo(arg);
      }
    }
  }

  private static final class SelectorFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final SelectorFuncfb47464a instance = new SelectorFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ListViewCompat) {
        ((ListViewCompat) v).setSelector(arg);
      }
    }
  }

  private static final class ShowDividersFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ShowDividersFunc8567756a instance = new ShowDividersFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setShowDividers(arg);
      }
    }
  }

  private static final class ShowTextFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final ShowTextFunc148d6054 instance = new ShowTextFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setShowText(arg);
      }
    }
  }

  private static final class ShowingForActionModeFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final ShowingForActionModeFunc148d6054 instance = new ShowingForActionModeFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setShowingForActionMode(arg);
      }
    }
  }

  private static final class SplitBackgroundFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final SplitBackgroundFuncfb47464a instance = new SplitBackgroundFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ActionBarContainer) {
        ((ActionBarContainer) v).setSplitBackground(arg);
      }
    }
  }

  private static final class SplitTrackFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final SplitTrackFunc148d6054 instance = new SplitTrackFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setSplitTrack(arg);
      }
    }
  }

  private static final class StackedBackgroundFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final StackedBackgroundFuncfb47464a instance = new StackedBackgroundFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ActionBarContainer) {
        ((ActionBarContainer) v).setStackedBackground(arg);
      }
    }
  }

  private static final class SubmitButtonEnabledFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final SubmitButtonEnabledFunc148d6054 instance = new SubmitButtonEnabledFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setSubmitButtonEnabled(arg);
      }
    }
  }

  private static final class SubtitleFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final SubtitleFunc8567756a instance = new SubtitleFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setSubtitle(arg);
      }
    }
  }

  private static final class SubtitleFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final SubtitleFuncc0af808b instance = new SubtitleFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof ActionBarContextView) {
        ((ActionBarContextView) v).setSubtitle(arg);
      }
      if (v instanceof Toolbar) {
        ((Toolbar) v).setSubtitle(arg);
      }
    }
  }

  private static final class SubtitleTextColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final SubtitleTextColorFunc8567756a instance = new SubtitleTextColorFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setSubtitleTextColor(arg);
      }
    }
  }

  private static final class SuggestionsAdapterFuncb430a5a1 implements Anvil.AttrFunc<CursorAdapter> {
    public static final SuggestionsAdapterFuncb430a5a1 instance = new SuggestionsAdapterFuncb430a5a1();

    public void apply(View v, final CursorAdapter arg, final CursorAdapter old) {
      if (v instanceof SearchView) {
        ((SearchView) v).setSuggestionsAdapter(arg);
      }
    }
  }

  private static final class SupportAllCapsFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final SupportAllCapsFunc148d6054 instance = new SupportAllCapsFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof AppCompatButton) {
        ((AppCompatButton) v).setSupportAllCaps(arg);
      }
    }
  }

  private static final class SupportBackgroundTintListFunc9e5e0e4e implements Anvil.AttrFunc<ColorStateList> {
    public static final SupportBackgroundTintListFunc9e5e0e4e instance = new SupportBackgroundTintListFunc9e5e0e4e();

    public void apply(View v, final ColorStateList arg, final ColorStateList old) {
      if (v instanceof AppCompatAutoCompleteTextView) {
        ((AppCompatAutoCompleteTextView) v).setSupportBackgroundTintList(arg);
      }
      if (v instanceof AppCompatButton) {
        ((AppCompatButton) v).setSupportBackgroundTintList(arg);
      }
      if (v instanceof AppCompatEditText) {
        ((AppCompatEditText) v).setSupportBackgroundTintList(arg);
      }
      if (v instanceof AppCompatImageButton) {
        ((AppCompatImageButton) v).setSupportBackgroundTintList(arg);
      }
      if (v instanceof AppCompatImageView) {
        ((AppCompatImageView) v).setSupportBackgroundTintList(arg);
      }
      if (v instanceof AppCompatMultiAutoCompleteTextView) {
        ((AppCompatMultiAutoCompleteTextView) v).setSupportBackgroundTintList(arg);
      }
      if (v instanceof AppCompatSpinner) {
        ((AppCompatSpinner) v).setSupportBackgroundTintList(arg);
      }
      if (v instanceof AppCompatTextView) {
        ((AppCompatTextView) v).setSupportBackgroundTintList(arg);
      }
    }
  }

  private static final class SupportBackgroundTintModeFuncabb7a84e implements Anvil.AttrFunc<PorterDuff.Mode> {
    public static final SupportBackgroundTintModeFuncabb7a84e instance = new SupportBackgroundTintModeFuncabb7a84e();

    public void apply(View v, final PorterDuff.Mode arg, final PorterDuff.Mode old) {
      if (v instanceof AppCompatAutoCompleteTextView) {
        ((AppCompatAutoCompleteTextView) v).setSupportBackgroundTintMode(arg);
      }
      if (v instanceof AppCompatButton) {
        ((AppCompatButton) v).setSupportBackgroundTintMode(arg);
      }
      if (v instanceof AppCompatEditText) {
        ((AppCompatEditText) v).setSupportBackgroundTintMode(arg);
      }
      if (v instanceof AppCompatImageButton) {
        ((AppCompatImageButton) v).setSupportBackgroundTintMode(arg);
      }
      if (v instanceof AppCompatImageView) {
        ((AppCompatImageView) v).setSupportBackgroundTintMode(arg);
      }
      if (v instanceof AppCompatMultiAutoCompleteTextView) {
        ((AppCompatMultiAutoCompleteTextView) v).setSupportBackgroundTintMode(arg);
      }
      if (v instanceof AppCompatSpinner) {
        ((AppCompatSpinner) v).setSupportBackgroundTintMode(arg);
      }
      if (v instanceof AppCompatTextView) {
        ((AppCompatTextView) v).setSupportBackgroundTintMode(arg);
      }
    }
  }

  private static final class SupportButtonTintListFunc9e5e0e4e implements Anvil.AttrFunc<ColorStateList> {
    public static final SupportButtonTintListFunc9e5e0e4e instance = new SupportButtonTintListFunc9e5e0e4e();

    public void apply(View v, final ColorStateList arg, final ColorStateList old) {
      if (v instanceof AppCompatCheckBox) {
        ((AppCompatCheckBox) v).setSupportButtonTintList(arg);
      }
      if (v instanceof AppCompatRadioButton) {
        ((AppCompatRadioButton) v).setSupportButtonTintList(arg);
      }
    }
  }

  private static final class SupportButtonTintModeFuncabb7a84e implements Anvil.AttrFunc<PorterDuff.Mode> {
    public static final SupportButtonTintModeFuncabb7a84e instance = new SupportButtonTintModeFuncabb7a84e();

    public void apply(View v, final PorterDuff.Mode arg, final PorterDuff.Mode old) {
      if (v instanceof AppCompatCheckBox) {
        ((AppCompatCheckBox) v).setSupportButtonTintMode(arg);
      }
      if (v instanceof AppCompatRadioButton) {
        ((AppCompatRadioButton) v).setSupportButtonTintMode(arg);
      }
    }
  }

  private static final class SwitchMinWidthFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final SwitchMinWidthFunc8567756a instance = new SwitchMinWidthFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setSwitchMinWidth(arg);
      }
    }
  }

  private static final class SwitchPaddingFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final SwitchPaddingFunc8567756a instance = new SwitchPaddingFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setSwitchPadding(arg);
      }
    }
  }

  private static final class SwitchTypefaceFunc53b4afb implements Anvil.AttrFunc<Typeface> {
    public static final SwitchTypefaceFunc53b4afb instance = new SwitchTypefaceFunc53b4afb();

    public void apply(View v, final Typeface arg, final Typeface old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setSwitchTypeface(arg);
      }
    }
  }

  private static final class TabContainerFunc1a5e642b implements Anvil.AttrFunc<ScrollingTabContainerView> {
    public static final TabContainerFunc1a5e642b instance = new TabContainerFunc1a5e642b();

    public void apply(View v, final ScrollingTabContainerView arg, final ScrollingTabContainerView old) {
      if (v instanceof ActionBarContainer) {
        ((ActionBarContainer) v).setTabContainer(arg);
      }
    }
  }

  private static final class TabSelectedFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final TabSelectedFunc8567756a instance = new TabSelectedFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ScrollingTabContainerView) {
        ((ScrollingTabContainerView) v).setTabSelected(arg);
      }
    }
  }

  private static final class TextOffFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final TextOffFuncc0af808b instance = new TextOffFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setTextOff(arg);
      }
    }
  }

  private static final class TextOnFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final TextOnFuncc0af808b instance = new TextOnFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setTextOn(arg);
      }
    }
  }

  private static final class ThumbDrawableFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final ThumbDrawableFuncfb47464a instance = new ThumbDrawableFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setThumbDrawable(arg);
      }
    }
  }

  private static final class ThumbResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ThumbResourceFunc8567756a instance = new ThumbResourceFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setThumbResource(arg);
      }
    }
  }

  private static final class ThumbTextPaddingFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ThumbTextPaddingFunc8567756a instance = new ThumbTextPaddingFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setThumbTextPadding(arg);
      }
    }
  }

  private static final class TitleFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final TitleFunc8567756a instance = new TitleFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setTitle(arg);
      }
    }
  }

  private static final class TitleFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final TitleFuncc0af808b instance = new TitleFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof ActionMenuItemView) {
        ((ActionMenuItemView) v).setTitle(arg);
      }
      if (v instanceof ListMenuItemView) {
        ((ListMenuItemView) v).setTitle(arg);
      }
      if (v instanceof ActionBarContextView) {
        ((ActionBarContextView) v).setTitle(arg);
      }
      if (v instanceof Toolbar) {
        ((Toolbar) v).setTitle(arg);
      }
    }
  }

  private static final class TitleOptionalFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final TitleOptionalFunc148d6054 instance = new TitleOptionalFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionBarContextView) {
        ((ActionBarContextView) v).setTitleOptional(arg);
      }
    }
  }

  private static final class TitleTextColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final TitleTextColorFunc8567756a instance = new TitleTextColorFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setTitleTextColor(arg);
      }
    }
  }

  private static final class TrackDrawableFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final TrackDrawableFuncfb47464a instance = new TrackDrawableFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setTrackDrawable(arg);
      }
    }
  }

  private static final class TrackResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final TrackResourceFunc8567756a instance = new TrackResourceFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setTrackResource(arg);
      }
    }
  }

  private static final class TransitioningFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final TransitioningFunc148d6054 instance = new TransitioningFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionBarContainer) {
        ((ActionBarContainer) v).setTransitioning(arg);
      }
    }
  }

  private static final class UiOptionsFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final UiOptionsFunc8567756a instance = new UiOptionsFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setUiOptions(arg);
      }
    }
  }

  private static final class VerticalGravityFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final VerticalGravityFunc8567756a instance = new VerticalGravityFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setVerticalGravity(arg);
      }
    }
  }

  private static final class VisibilityFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final VisibilityFunc8567756a instance = new VisibilityFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActionBarContainer) {
        ((ActionBarContainer) v).setVisibility(arg);
      }
      if (v instanceof ViewStubCompat) {
        ((ViewStubCompat) v).setVisibility(arg);
      }
    }
  }

  private static final class WeightSumFunce0893188 implements Anvil.AttrFunc<Float> {
    public static final WeightSumFunce0893188 instance = new WeightSumFunce0893188();

    public void apply(View v, final Float arg, final Float old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setWeightSum(arg);
      }
    }
  }

  private static final class WindowCallbackFunc13cc8159 implements Anvil.AttrFunc<Window.Callback> {
    public static final WindowCallbackFunc13cc8159 instance = new WindowCallbackFunc13cc8159();

    public void apply(View v, final Window.Callback arg, final Window.Callback old) {
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setWindowCallback(arg);
      }
    }
  }

  private static final class WindowTitleFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final WindowTitleFuncc0af808b instance = new WindowTitleFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof ActionBarOverlayLayout) {
        ((ActionBarOverlayLayout) v).setWindowTitle(arg);
      }
    }
  }
}
