package trikita.anvil;

import android.graphics.Rect;
import android.graphics.Typeface;
import android.graphics.drawable.Drawable;
import android.support.v4.view.ActionProvider;
import android.support.v7.view.menu.ExpandedMenuView;
import android.support.v7.view.menu.ListMenuItemView;
import android.support.v7.widget.ActionBarContainer;
import android.support.v7.widget.ActionMenuView;
import android.support.v7.widget.ActivityChooserView;
import android.support.v7.widget.AppCompatCheckedTextView;
import android.support.v7.widget.AppCompatRatingBar;
import android.support.v7.widget.AppCompatSeekBar;
import android.support.v7.widget.ButtonBarLayout;
import android.support.v7.widget.ContentFrameLayout;
import android.support.v7.widget.DialogTitle;
import android.support.v7.widget.FitWindowsFrameLayout;
import android.support.v7.widget.FitWindowsLinearLayout;
import android.support.v7.widget.FitWindowsViewGroup;
import android.support.v7.widget.LinearLayoutCompat;
import android.support.v7.widget.ListViewCompat;
import android.support.v7.widget.SwitchCompat;
import android.support.v7.widget.Toolbar;
import android.support.v7.widget.ViewStubCompat;
import android.view.LayoutInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.PopupWindow;
import java.lang.Boolean;
import java.lang.CharSequence;
import java.lang.Float;
import java.lang.Integer;
import java.lang.Void;

/**
 * DSL for creating views and settings their attributes.
 * This file has been generated by {@code gradle generateAppCompatv7DSL}.
 * It contains views and their setters from the library appcompat-v7.
 * Please, don't edit it manually unless for debugging.
 */
public final class AppCompatv7DSL extends BaseDSL {
  public static AppCompatv7DSL.ViewClassResult expandedMenuView() {
    return v(ExpandedMenuView.class);
  }

  public static Void expandedMenuView(Anvil.Renderable r) {
    return v(ExpandedMenuView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult listMenuItemView() {
    return v(ListMenuItemView.class);
  }

  public static Void listMenuItemView(Anvil.Renderable r) {
    return v(ListMenuItemView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult actionBarContainer() {
    return v(ActionBarContainer.class);
  }

  public static Void actionBarContainer(Anvil.Renderable r) {
    return v(ActionBarContainer.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult actionMenuView() {
    return v(ActionMenuView.class);
  }

  public static Void actionMenuView(Anvil.Renderable r) {
    return v(ActionMenuView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult activityChooserView() {
    return v(ActivityChooserView.class);
  }

  public static Void activityChooserView(Anvil.Renderable r) {
    return v(ActivityChooserView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatCheckedTextView() {
    return v(AppCompatCheckedTextView.class);
  }

  public static Void appCompatCheckedTextView(Anvil.Renderable r) {
    return v(AppCompatCheckedTextView.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatRatingBar() {
    return v(AppCompatRatingBar.class);
  }

  public static Void appCompatRatingBar(Anvil.Renderable r) {
    return v(AppCompatRatingBar.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult appCompatSeekBar() {
    return v(AppCompatSeekBar.class);
  }

  public static Void appCompatSeekBar(Anvil.Renderable r) {
    return v(AppCompatSeekBar.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult buttonBarLayout() {
    return v(ButtonBarLayout.class);
  }

  public static Void buttonBarLayout(Anvil.Renderable r) {
    return v(ButtonBarLayout.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult contentFrameLayout() {
    return v(ContentFrameLayout.class);
  }

  public static Void contentFrameLayout(Anvil.Renderable r) {
    return v(ContentFrameLayout.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult dialogTitle() {
    return v(DialogTitle.class);
  }

  public static Void dialogTitle(Anvil.Renderable r) {
    return v(DialogTitle.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult fitWindowsFrameLayout() {
    return v(FitWindowsFrameLayout.class);
  }

  public static Void fitWindowsFrameLayout(Anvil.Renderable r) {
    return v(FitWindowsFrameLayout.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult fitWindowsLinearLayout() {
    return v(FitWindowsLinearLayout.class);
  }

  public static Void fitWindowsLinearLayout(Anvil.Renderable r) {
    return v(FitWindowsLinearLayout.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult linearLayoutCompat() {
    return v(LinearLayoutCompat.class);
  }

  public static Void linearLayoutCompat(Anvil.Renderable r) {
    return v(LinearLayoutCompat.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult listViewCompat() {
    return v(ListViewCompat.class);
  }

  public static Void listViewCompat(Anvil.Renderable r) {
    return v(ListViewCompat.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult switchCompat() {
    return v(SwitchCompat.class);
  }

  public static Void switchCompat(Anvil.Renderable r) {
    return v(SwitchCompat.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult toolbar() {
    return v(Toolbar.class);
  }

  public static Void toolbar(Anvil.Renderable r) {
    return v(Toolbar.class, r);
  }

  public static AppCompatv7DSL.ViewClassResult viewStubCompat() {
    return v(ViewStubCompat.class);
  }

  public static Void viewStubCompat(Anvil.Renderable r) {
    return v(ViewStubCompat.class, r);
  }

  public static Void allowStacking(boolean arg) {
    return AppCompatv7DSL.attr(AllowStackingFunc148d6054.instance, arg);
  }

  public static Void attachListener(ContentFrameLayout.OnAttachListener arg) {
    return AppCompatv7DSL.attr(AttachListenerFunc3ca76dcd.instance, arg);
  }

  public static Void baselineAligned(boolean arg) {
    return AppCompatv7DSL.attr(BaselineAlignedFunc148d6054.instance, arg);
  }

  public static Void baselineAlignedChildIndex(int arg) {
    return AppCompatv7DSL.attr(BaselineAlignedChildIndexFunc8567756a.instance, arg);
  }

  public static Void checkMarkDrawable(int arg) {
    return AppCompatv7DSL.attr(CheckMarkDrawableFunc8567756a.instance, arg);
  }

  public static Void checkable(boolean arg) {
    return AppCompatv7DSL.attr(CheckableFunc148d6054.instance, arg);
  }

  public static Void checked(boolean arg) {
    return AppCompatv7DSL.attr(CheckedFunc148d6054.instance, arg);
  }

  public static Void collapsible(boolean arg) {
    return AppCompatv7DSL.attr(CollapsibleFunc148d6054.instance, arg);
  }

  public static Void defaultActionButtonContentDescription(int arg) {
    return AppCompatv7DSL.attr(DefaultActionButtonContentDescriptionFunc8567756a.instance, arg);
  }

  public static Void dividerDrawable(Drawable arg) {
    return AppCompatv7DSL.attr(DividerDrawableFuncfb47464a.instance, arg);
  }

  public static Void dividerPadding(int arg) {
    return AppCompatv7DSL.attr(DividerPaddingFunc8567756a.instance, arg);
  }

  public static Void expandActivityOverflowButtonContentDescription(int arg) {
    return AppCompatv7DSL.attr(ExpandActivityOverflowButtonContentDescriptionFunc8567756a.instance, arg);
  }

  public static Void expandActivityOverflowButtonDrawable(Drawable arg) {
    return AppCompatv7DSL.attr(ExpandActivityOverflowButtonDrawableFuncfb47464a.instance, arg);
  }

  public static Void expandedActionViewsExclusive(boolean arg) {
    return AppCompatv7DSL.attr(ExpandedActionViewsExclusiveFunc148d6054.instance, arg);
  }

  public static Void forceShowIcon(boolean arg) {
    return AppCompatv7DSL.attr(ForceShowIconFunc148d6054.instance, arg);
  }

  public static Void gravity(int arg) {
    return AppCompatv7DSL.attr(GravityFunc8567756a.instance, arg);
  }

  public static Void horizontalGravity(int arg) {
    return AppCompatv7DSL.attr(HorizontalGravityFunc8567756a.instance, arg);
  }

  public static Void icon(Drawable arg) {
    return AppCompatv7DSL.attr(IconFuncfb47464a.instance, arg);
  }

  public static Void inflatedId(int arg) {
    return AppCompatv7DSL.attr(InflatedIdFunc8567756a.instance, arg);
  }

  public static Void initialActivityCount(int arg) {
    return AppCompatv7DSL.attr(InitialActivityCountFunc8567756a.instance, arg);
  }

  public static Void layoutInflater(LayoutInflater arg) {
    return AppCompatv7DSL.attr(LayoutInflaterFunc3f91d1f.instance, arg);
  }

  public static Void layoutResource(int arg) {
    return AppCompatv7DSL.attr(LayoutResourceFunc8567756a.instance, arg);
  }

  public static Void logo(Drawable arg) {
    return AppCompatv7DSL.attr(LogoFuncfb47464a.instance, arg);
  }

  public static Void logo(int arg) {
    return AppCompatv7DSL.attr(LogoFunc8567756a.instance, arg);
  }

  public static Void logoDescription(int arg) {
    return AppCompatv7DSL.attr(LogoDescriptionFunc8567756a.instance, arg);
  }

  public static Void logoDescription(CharSequence arg) {
    return AppCompatv7DSL.attr(LogoDescriptionFuncc0af808b.instance, arg);
  }

  public static Void measureWithLargestChildEnabled(boolean arg) {
    return AppCompatv7DSL.attr(MeasureWithLargestChildEnabledFunc148d6054.instance, arg);
  }

  public static Void navigationContentDescription(int arg) {
    return AppCompatv7DSL.attr(NavigationContentDescriptionFunc8567756a.instance, arg);
  }

  public static Void navigationContentDescription(CharSequence arg) {
    return AppCompatv7DSL.attr(NavigationContentDescriptionFuncc0af808b.instance, arg);
  }

  public static Void navigationIcon(Drawable arg) {
    return AppCompatv7DSL.attr(NavigationIconFuncfb47464a.instance, arg);
  }

  public static Void navigationIcon(int arg) {
    return AppCompatv7DSL.attr(NavigationIconFunc8567756a.instance, arg);
  }

  public static Void navigationOnClickListener(View.OnClickListener arg) {
    return AppCompatv7DSL.attr(NavigationOnClickListenerFunc79a13a5e.instance, arg);
  }

  public static Void onDismiss(PopupWindow.OnDismissListener arg) {
    return AppCompatv7DSL.attr(OnDismissFunc6b0eb982.instance, arg);
  }

  public static Void onFitSystemWindows(FitWindowsViewGroup.OnFitSystemWindowsListener arg) {
    return AppCompatv7DSL.attr(OnFitSystemWindowsFuncad8dd5d7.instance, arg);
  }

  public static Void onInflate(ViewStubCompat.OnInflateListener arg) {
    return AppCompatv7DSL.attr(OnInflateFuncb0ac3dfe.instance, arg);
  }

  public static Void onMenuItemClick(ActionMenuView.OnMenuItemClickListener arg) {
    return AppCompatv7DSL.attr(OnMenuItemClickFuncd1d929f2.instance, arg);
  }

  public static Void onMenuItemClick(Toolbar.OnMenuItemClickListener arg) {
    return AppCompatv7DSL.attr(OnMenuItemClickFunc68ab335d.instance, arg);
  }

  public static Void orientation(int arg) {
    return AppCompatv7DSL.attr(OrientationFunc8567756a.instance, arg);
  }

  public static Void overflowIcon(Drawable arg) {
    return AppCompatv7DSL.attr(OverflowIconFuncfb47464a.instance, arg);
  }

  public static Void overflowReserved(boolean arg) {
    return AppCompatv7DSL.attr(OverflowReservedFunc148d6054.instance, arg);
  }

  public static Void popupTheme(int arg) {
    return AppCompatv7DSL.attr(PopupThemeFunc8567756a.instance, arg);
  }

  public static Void primaryBackground(Drawable arg) {
    return AppCompatv7DSL.attr(PrimaryBackgroundFuncfb47464a.instance, arg);
  }

  public static Void provider(ActionProvider arg) {
    return AppCompatv7DSL.attr(ProviderFunc66da8dbe.instance, arg);
  }

  public static Void selector(Drawable arg) {
    return AppCompatv7DSL.attr(SelectorFuncfb47464a.instance, arg);
  }

  public static Void showDividers(int arg) {
    return AppCompatv7DSL.attr(ShowDividersFunc8567756a.instance, arg);
  }

  public static Void showText(boolean arg) {
    return AppCompatv7DSL.attr(ShowTextFunc148d6054.instance, arg);
  }

  public static Void splitBackground(Drawable arg) {
    return AppCompatv7DSL.attr(SplitBackgroundFuncfb47464a.instance, arg);
  }

  public static Void splitTrack(boolean arg) {
    return AppCompatv7DSL.attr(SplitTrackFunc148d6054.instance, arg);
  }

  public static Void stackedBackground(Drawable arg) {
    return AppCompatv7DSL.attr(StackedBackgroundFuncfb47464a.instance, arg);
  }

  public static Void subtitle(int arg) {
    return AppCompatv7DSL.attr(SubtitleFunc8567756a.instance, arg);
  }

  public static Void subtitle(CharSequence arg) {
    return AppCompatv7DSL.attr(SubtitleFuncc0af808b.instance, arg);
  }

  public static Void subtitleTextColor(int arg) {
    return AppCompatv7DSL.attr(SubtitleTextColorFunc8567756a.instance, arg);
  }

  public static Void switchMinWidth(int arg) {
    return AppCompatv7DSL.attr(SwitchMinWidthFunc8567756a.instance, arg);
  }

  public static Void switchPadding(int arg) {
    return AppCompatv7DSL.attr(SwitchPaddingFunc8567756a.instance, arg);
  }

  public static Void switchTypeface(Typeface arg) {
    return AppCompatv7DSL.attr(SwitchTypefaceFunc53b4afb.instance, arg);
  }

  public static Void textOff(CharSequence arg) {
    return AppCompatv7DSL.attr(TextOffFuncc0af808b.instance, arg);
  }

  public static Void textOn(CharSequence arg) {
    return AppCompatv7DSL.attr(TextOnFuncc0af808b.instance, arg);
  }

  public static Void thumbDrawable(Drawable arg) {
    return AppCompatv7DSL.attr(ThumbDrawableFuncfb47464a.instance, arg);
  }

  public static Void thumbResource(int arg) {
    return AppCompatv7DSL.attr(ThumbResourceFunc8567756a.instance, arg);
  }

  public static Void thumbTextPadding(int arg) {
    return AppCompatv7DSL.attr(ThumbTextPaddingFunc8567756a.instance, arg);
  }

  public static Void title(int arg) {
    return AppCompatv7DSL.attr(TitleFunc8567756a.instance, arg);
  }

  public static Void title(CharSequence arg) {
    return AppCompatv7DSL.attr(TitleFuncc0af808b.instance, arg);
  }

  public static Void titleTextColor(int arg) {
    return AppCompatv7DSL.attr(TitleTextColorFunc8567756a.instance, arg);
  }

  public static Void trackDrawable(Drawable arg) {
    return AppCompatv7DSL.attr(TrackDrawableFuncfb47464a.instance, arg);
  }

  public static Void trackResource(int arg) {
    return AppCompatv7DSL.attr(TrackResourceFunc8567756a.instance, arg);
  }

  public static Void verticalGravity(int arg) {
    return AppCompatv7DSL.attr(VerticalGravityFunc8567756a.instance, arg);
  }

  public static Void visibility(int arg) {
    return AppCompatv7DSL.attr(VisibilityFunc8567756a.instance, arg);
  }

  public static Void weightSum(float arg) {
    return AppCompatv7DSL.attr(WeightSumFunce0893188.instance, arg);
  }

  private static final class AllowStackingFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final AllowStackingFunc148d6054 instance = new AllowStackingFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ButtonBarLayout) {
        ((ButtonBarLayout) v).setAllowStacking(arg);
      }
    }
  }

  private static final class AttachListenerFunc3ca76dcd implements Anvil.AttrFunc<ContentFrameLayout.OnAttachListener> {
    public static final AttachListenerFunc3ca76dcd instance = new AttachListenerFunc3ca76dcd();

    public void apply(View v, final ContentFrameLayout.OnAttachListener arg, final ContentFrameLayout.OnAttachListener old) {
      if (v instanceof ContentFrameLayout) {
        ((ContentFrameLayout) v).setAttachListener(arg);
      }
    }
  }

  private static final class BaselineAlignedFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final BaselineAlignedFunc148d6054 instance = new BaselineAlignedFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setBaselineAligned(arg);
      }
    }
  }

  private static final class BaselineAlignedChildIndexFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final BaselineAlignedChildIndexFunc8567756a instance = new BaselineAlignedChildIndexFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setBaselineAlignedChildIndex(arg);
      }
    }
  }

  private static final class CheckMarkDrawableFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final CheckMarkDrawableFunc8567756a instance = new CheckMarkDrawableFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof AppCompatCheckedTextView) {
        ((AppCompatCheckedTextView) v).setCheckMarkDrawable(arg);
      }
    }
  }

  private static final class CheckableFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final CheckableFunc148d6054 instance = new CheckableFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ListMenuItemView) {
        ((ListMenuItemView) v).setCheckable(arg);
      }
    }
  }

  private static final class CheckedFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final CheckedFunc148d6054 instance = new CheckedFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ListMenuItemView) {
        ((ListMenuItemView) v).setChecked(arg);
      }
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setChecked(arg);
      }
    }
  }

  private static final class CollapsibleFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final CollapsibleFunc148d6054 instance = new CollapsibleFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setCollapsible(arg);
      }
    }
  }

  private static final class DefaultActionButtonContentDescriptionFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final DefaultActionButtonContentDescriptionFunc8567756a instance = new DefaultActionButtonContentDescriptionFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setDefaultActionButtonContentDescription(arg);
      }
    }
  }

  private static final class DividerDrawableFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final DividerDrawableFuncfb47464a instance = new DividerDrawableFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setDividerDrawable(arg);
      }
    }
  }

  private static final class DividerPaddingFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final DividerPaddingFunc8567756a instance = new DividerPaddingFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setDividerPadding(arg);
      }
    }
  }

  private static final class ExpandActivityOverflowButtonContentDescriptionFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ExpandActivityOverflowButtonContentDescriptionFunc8567756a instance = new ExpandActivityOverflowButtonContentDescriptionFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setExpandActivityOverflowButtonContentDescription(arg);
      }
    }
  }

  private static final class ExpandActivityOverflowButtonDrawableFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final ExpandActivityOverflowButtonDrawableFuncfb47464a instance = new ExpandActivityOverflowButtonDrawableFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setExpandActivityOverflowButtonDrawable(arg);
      }
    }
  }

  private static final class ExpandedActionViewsExclusiveFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final ExpandedActionViewsExclusiveFunc148d6054 instance = new ExpandedActionViewsExclusiveFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionMenuView) {
        ((ActionMenuView) v).setExpandedActionViewsExclusive(arg);
      }
    }
  }

  private static final class ForceShowIconFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final ForceShowIconFunc148d6054 instance = new ForceShowIconFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ListMenuItemView) {
        ((ListMenuItemView) v).setForceShowIcon(arg);
      }
    }
  }

  private static final class GravityFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final GravityFunc8567756a instance = new GravityFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setGravity(arg);
      }
    }
  }

  private static final class HorizontalGravityFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final HorizontalGravityFunc8567756a instance = new HorizontalGravityFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setHorizontalGravity(arg);
      }
    }
  }

  private static final class IconFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final IconFuncfb47464a instance = new IconFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ListMenuItemView) {
        ((ListMenuItemView) v).setIcon(arg);
      }
    }
  }

  private static final class InflatedIdFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final InflatedIdFunc8567756a instance = new InflatedIdFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ViewStubCompat) {
        ((ViewStubCompat) v).setInflatedId(arg);
      }
    }
  }

  private static final class InitialActivityCountFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final InitialActivityCountFunc8567756a instance = new InitialActivityCountFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setInitialActivityCount(arg);
      }
    }
  }

  private static final class LayoutInflaterFunc3f91d1f implements Anvil.AttrFunc<LayoutInflater> {
    public static final LayoutInflaterFunc3f91d1f instance = new LayoutInflaterFunc3f91d1f();

    public void apply(View v, final LayoutInflater arg, final LayoutInflater old) {
      if (v instanceof ViewStubCompat) {
        ((ViewStubCompat) v).setLayoutInflater(arg);
      }
    }
  }

  private static final class LayoutResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final LayoutResourceFunc8567756a instance = new LayoutResourceFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ViewStubCompat) {
        ((ViewStubCompat) v).setLayoutResource(arg);
      }
    }
  }

  private static final class LogoFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final LogoFuncfb47464a instance = new LogoFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setLogo(arg);
      }
    }
  }

  private static final class LogoFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final LogoFunc8567756a instance = new LogoFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setLogo(arg);
      }
    }
  }

  private static final class LogoDescriptionFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final LogoDescriptionFunc8567756a instance = new LogoDescriptionFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setLogoDescription(arg);
      }
    }
  }

  private static final class LogoDescriptionFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final LogoDescriptionFuncc0af808b instance = new LogoDescriptionFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setLogoDescription(arg);
      }
    }
  }

  private static final class MeasureWithLargestChildEnabledFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final MeasureWithLargestChildEnabledFunc148d6054 instance = new MeasureWithLargestChildEnabledFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setMeasureWithLargestChildEnabled(arg);
      }
    }
  }

  private static final class NavigationContentDescriptionFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final NavigationContentDescriptionFunc8567756a instance = new NavigationContentDescriptionFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setNavigationContentDescription(arg);
      }
    }
  }

  private static final class NavigationContentDescriptionFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final NavigationContentDescriptionFuncc0af808b instance = new NavigationContentDescriptionFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setNavigationContentDescription(arg);
      }
    }
  }

  private static final class NavigationIconFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final NavigationIconFuncfb47464a instance = new NavigationIconFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setNavigationIcon(arg);
      }
    }
  }

  private static final class NavigationIconFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final NavigationIconFunc8567756a instance = new NavigationIconFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setNavigationIcon(arg);
      }
    }
  }

  private static final class NavigationOnClickListenerFunc79a13a5e implements Anvil.AttrFunc<View.OnClickListener> {
    public static final NavigationOnClickListenerFunc79a13a5e instance = new NavigationOnClickListenerFunc79a13a5e();

    public void apply(View v, final View.OnClickListener arg, final View.OnClickListener old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setNavigationOnClickListener(arg);
      }
    }
  }

  private static final class OnDismissFunc6b0eb982 implements Anvil.AttrFunc<PopupWindow.OnDismissListener> {
    public static final OnDismissFunc6b0eb982 instance = new OnDismissFunc6b0eb982();

    public void apply(View v, final PopupWindow.OnDismissListener arg, final PopupWindow.OnDismissListener old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setOnDismissListener(new PopupWindow.OnDismissListener() {
          public void onDismiss() {
            arg.onDismiss();
            Anvil.render();
          }
        });
      }
    }
  }

  private static final class OnFitSystemWindowsFuncad8dd5d7 implements Anvil.AttrFunc<FitWindowsViewGroup.OnFitSystemWindowsListener> {
    public static final OnFitSystemWindowsFuncad8dd5d7 instance = new OnFitSystemWindowsFuncad8dd5d7();

    public void apply(View v, final FitWindowsViewGroup.OnFitSystemWindowsListener arg, final FitWindowsViewGroup.OnFitSystemWindowsListener old) {
      if (v instanceof FitWindowsFrameLayout) {
        ((FitWindowsFrameLayout) v).setOnFitSystemWindowsListener(new FitWindowsViewGroup.OnFitSystemWindowsListener() {
          public void onFitSystemWindows(Rect a0) {
            arg.onFitSystemWindows(a0);
            Anvil.render();
          }
        });
      }
      if (v instanceof FitWindowsLinearLayout) {
        ((FitWindowsLinearLayout) v).setOnFitSystemWindowsListener(new FitWindowsViewGroup.OnFitSystemWindowsListener() {
          public void onFitSystemWindows(Rect a0) {
            arg.onFitSystemWindows(a0);
            Anvil.render();
          }
        });
      }
    }
  }

  private static final class OnInflateFuncb0ac3dfe implements Anvil.AttrFunc<ViewStubCompat.OnInflateListener> {
    public static final OnInflateFuncb0ac3dfe instance = new OnInflateFuncb0ac3dfe();

    public void apply(View v, final ViewStubCompat.OnInflateListener arg, final ViewStubCompat.OnInflateListener old) {
      if (v instanceof ViewStubCompat) {
        ((ViewStubCompat) v).setOnInflateListener(new ViewStubCompat.OnInflateListener() {
          public void onInflate(ViewStubCompat a0, View a1) {
            arg.onInflate(a0, a1);
            Anvil.render();
          }
        });
      }
    }
  }

  private static final class OnMenuItemClickFuncd1d929f2 implements Anvil.AttrFunc<ActionMenuView.OnMenuItemClickListener> {
    public static final OnMenuItemClickFuncd1d929f2 instance = new OnMenuItemClickFuncd1d929f2();

    public void apply(View v, final ActionMenuView.OnMenuItemClickListener arg, final ActionMenuView.OnMenuItemClickListener old) {
      if (v instanceof ActionMenuView) {
        ((ActionMenuView) v).setOnMenuItemClickListener(new ActionMenuView.OnMenuItemClickListener() {
          public boolean onMenuItemClick(MenuItem a0) {
            boolean r = arg.onMenuItemClick(a0);
            Anvil.render();
            return r;
          }
        });
      }
    }
  }

  private static final class OnMenuItemClickFunc68ab335d implements Anvil.AttrFunc<Toolbar.OnMenuItemClickListener> {
    public static final OnMenuItemClickFunc68ab335d instance = new OnMenuItemClickFunc68ab335d();

    public void apply(View v, final Toolbar.OnMenuItemClickListener arg, final Toolbar.OnMenuItemClickListener old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setOnMenuItemClickListener(new Toolbar.OnMenuItemClickListener() {
          public boolean onMenuItemClick(MenuItem a0) {
            boolean r = arg.onMenuItemClick(a0);
            Anvil.render();
            return r;
          }
        });
      }
    }
  }

  private static final class OrientationFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final OrientationFunc8567756a instance = new OrientationFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setOrientation(arg);
      }
    }
  }

  private static final class OverflowIconFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final OverflowIconFuncfb47464a instance = new OverflowIconFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ActionMenuView) {
        ((ActionMenuView) v).setOverflowIcon(arg);
      }
      if (v instanceof Toolbar) {
        ((Toolbar) v).setOverflowIcon(arg);
      }
    }
  }

  private static final class OverflowReservedFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final OverflowReservedFunc148d6054 instance = new OverflowReservedFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof ActionMenuView) {
        ((ActionMenuView) v).setOverflowReserved(arg);
      }
    }
  }

  private static final class PopupThemeFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final PopupThemeFunc8567756a instance = new PopupThemeFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ActionMenuView) {
        ((ActionMenuView) v).setPopupTheme(arg);
      }
      if (v instanceof Toolbar) {
        ((Toolbar) v).setPopupTheme(arg);
      }
    }
  }

  private static final class PrimaryBackgroundFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final PrimaryBackgroundFuncfb47464a instance = new PrimaryBackgroundFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ActionBarContainer) {
        ((ActionBarContainer) v).setPrimaryBackground(arg);
      }
    }
  }

  private static final class ProviderFunc66da8dbe implements Anvil.AttrFunc<ActionProvider> {
    public static final ProviderFunc66da8dbe instance = new ProviderFunc66da8dbe();

    public void apply(View v, final ActionProvider arg, final ActionProvider old) {
      if (v instanceof ActivityChooserView) {
        ((ActivityChooserView) v).setProvider(arg);
      }
    }
  }

  private static final class SelectorFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final SelectorFuncfb47464a instance = new SelectorFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ListViewCompat) {
        ((ListViewCompat) v).setSelector(arg);
      }
    }
  }

  private static final class ShowDividersFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ShowDividersFunc8567756a instance = new ShowDividersFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setShowDividers(arg);
      }
    }
  }

  private static final class ShowTextFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final ShowTextFunc148d6054 instance = new ShowTextFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setShowText(arg);
      }
    }
  }

  private static final class SplitBackgroundFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final SplitBackgroundFuncfb47464a instance = new SplitBackgroundFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ActionBarContainer) {
        ((ActionBarContainer) v).setSplitBackground(arg);
      }
    }
  }

  private static final class SplitTrackFunc148d6054 implements Anvil.AttrFunc<Boolean> {
    public static final SplitTrackFunc148d6054 instance = new SplitTrackFunc148d6054();

    public void apply(View v, final Boolean arg, final Boolean old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setSplitTrack(arg);
      }
    }
  }

  private static final class StackedBackgroundFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final StackedBackgroundFuncfb47464a instance = new StackedBackgroundFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof ActionBarContainer) {
        ((ActionBarContainer) v).setStackedBackground(arg);
      }
    }
  }

  private static final class SubtitleFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final SubtitleFunc8567756a instance = new SubtitleFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setSubtitle(arg);
      }
    }
  }

  private static final class SubtitleFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final SubtitleFuncc0af808b instance = new SubtitleFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setSubtitle(arg);
      }
    }
  }

  private static final class SubtitleTextColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final SubtitleTextColorFunc8567756a instance = new SubtitleTextColorFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setSubtitleTextColor(arg);
      }
    }
  }

  private static final class SwitchMinWidthFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final SwitchMinWidthFunc8567756a instance = new SwitchMinWidthFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setSwitchMinWidth(arg);
      }
    }
  }

  private static final class SwitchPaddingFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final SwitchPaddingFunc8567756a instance = new SwitchPaddingFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setSwitchPadding(arg);
      }
    }
  }

  private static final class SwitchTypefaceFunc53b4afb implements Anvil.AttrFunc<Typeface> {
    public static final SwitchTypefaceFunc53b4afb instance = new SwitchTypefaceFunc53b4afb();

    public void apply(View v, final Typeface arg, final Typeface old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setSwitchTypeface(arg);
      }
    }
  }

  private static final class TextOffFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final TextOffFuncc0af808b instance = new TextOffFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setTextOff(arg);
      }
    }
  }

  private static final class TextOnFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final TextOnFuncc0af808b instance = new TextOnFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setTextOn(arg);
      }
    }
  }

  private static final class ThumbDrawableFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final ThumbDrawableFuncfb47464a instance = new ThumbDrawableFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setThumbDrawable(arg);
      }
    }
  }

  private static final class ThumbResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ThumbResourceFunc8567756a instance = new ThumbResourceFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setThumbResource(arg);
      }
    }
  }

  private static final class ThumbTextPaddingFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final ThumbTextPaddingFunc8567756a instance = new ThumbTextPaddingFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setThumbTextPadding(arg);
      }
    }
  }

  private static final class TitleFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final TitleFunc8567756a instance = new TitleFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setTitle(arg);
      }
    }
  }

  private static final class TitleFuncc0af808b implements Anvil.AttrFunc<CharSequence> {
    public static final TitleFuncc0af808b instance = new TitleFuncc0af808b();

    public void apply(View v, final CharSequence arg, final CharSequence old) {
      if (v instanceof ListMenuItemView) {
        ((ListMenuItemView) v).setTitle(arg);
      }
      if (v instanceof Toolbar) {
        ((Toolbar) v).setTitle(arg);
      }
    }
  }

  private static final class TitleTextColorFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final TitleTextColorFunc8567756a instance = new TitleTextColorFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof Toolbar) {
        ((Toolbar) v).setTitleTextColor(arg);
      }
    }
  }

  private static final class TrackDrawableFuncfb47464a implements Anvil.AttrFunc<Drawable> {
    public static final TrackDrawableFuncfb47464a instance = new TrackDrawableFuncfb47464a();

    public void apply(View v, final Drawable arg, final Drawable old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setTrackDrawable(arg);
      }
    }
  }

  private static final class TrackResourceFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final TrackResourceFunc8567756a instance = new TrackResourceFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof SwitchCompat) {
        ((SwitchCompat) v).setTrackResource(arg);
      }
    }
  }

  private static final class VerticalGravityFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final VerticalGravityFunc8567756a instance = new VerticalGravityFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setVerticalGravity(arg);
      }
    }
  }

  private static final class VisibilityFunc8567756a implements Anvil.AttrFunc<Integer> {
    public static final VisibilityFunc8567756a instance = new VisibilityFunc8567756a();

    public void apply(View v, final Integer arg, final Integer old) {
      if (v instanceof ViewStubCompat) {
        ((ViewStubCompat) v).setVisibility(arg);
      }
    }
  }

  private static final class WeightSumFunce0893188 implements Anvil.AttrFunc<Float> {
    public static final WeightSumFunce0893188 instance = new WeightSumFunce0893188();

    public void apply(View v, final Float arg, final Float old) {
      if (v instanceof LinearLayoutCompat) {
        ((LinearLayoutCompat) v).setWeightSum(arg);
      }
    }
  }
}
