@file:Suppress("DEPRECATION", "UNCHECKED_CAST", "MemberVisibilityCanBePrivate", "unused")

package dev.inkremental.dsl.yoga

import android.view.View
import trikita.anvil.Anvil

/**
 * DSL for creating views and settings their attributes.
 * This file has been generated by
 * {@code gradle generateYogaDsl}
 * It contains views and their setters for the library yogalayout.
 * Please, don't edit it manually unless for debugging.
 */
object YogaSetter : Anvil.AttributeSetter<Any?> {
  override fun set(
    v: View,
    name: String,
    arg: Any?,
    old: Any?
  ): Boolean = when (name) {
    else -> false
  }
}
